- package.json
Tiny fix. making the settings in vscode be "ReScript" instead of "Example configuration"
> renaming config to rescript

- grammars/rescript.tmLanguage.json
> Fix open and include syntax highlighting

- server/src/constants.ts
- server/src/server.ts
In certain cases the native bsc binaries might be put in an unknown location on the file system. Example: yarn workspaces. The only other guarantee we have is that the node bsc should be available in the `project root + ./node_modules/.bin` cf. package.json. See [npm package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin) or [yarn package.json](https://classic.yarnpkg.com/en/docs/package-json#bin) and [yarn run](https://classic.yarnpkg.com/en/docs/cli/run#toc-yarn-run-script)
> Tweak bsc path algorithm.

- server/src/server.ts
see issue #55
on some sytems the `.compiler.log` was not readable after
_chokidar_ called _sendUpdateDiagnostics_. Setting
_awaitWriteFinish_ as an option fixes the issue
> fix watcher race condition

- server/src/RescriptEditorSupport.ts
- server/src/server.ts
> exec -> execSync for invoking RescriptEditorSupport binary

- server/src/RescriptEditorSupport.ts
> execSync -> execFileSync for RescriptEditorSupport binary invocation

- grammars/rescript.tmLanguage.json
Some of keywords are from OCaml that are not from Rescript docs, Hence i filter out all keyword specified in docs from keyword list specified in grammer
Here is the fixes
List of keyword that were specified in grammer json but not in docs
`nonrec, val, then, fun, virtual, do, done, catch, begin, pub, or, library, class, new, finally, inherit, export, object, pri, private, import, raise, functor`
List of keyword that were specified in rescript docs but not in grammer json
`true, include, open, when, with, false, type`
> Fix keyword list specified in grammer

- server/src/server.ts
This was discussed on the forum [here](https://forum.rescript-lang.org/t/rescript-emacs-support-with-rescript-vscode/1056).  I understand your focus is on VS code so I'm not taking for granted that this will be accepted -- obviously I think the patch should be applied though :-)
Not sure if it helps, but I don't expect to be coming back with any requests to change behaviour beyond this in order to support emacs.  Everything already seems workable as-is, the emacs lsp-mode.el people target feature parity with vscode, and also provide general-purpose message processing hooks to allow ad-hoc server-dependent treatment.
Should I add an explicit comment next to the command line switch code along the lines below?
```
// The fact that rescript-vscode uses LSP under the hood is an implementation …
```
> Add --stdio switch

- server/src/constants.ts
- server/src/server.ts
- server/src/utils.ts
Need to find the new package's name for the formatter.
Fixes #104
> Work with the newest rescript package

- analysis/.depend
- analysis/src/Protocol.ml
- analysis/tests/src/expected/Complete.res.txt
String.escaped doesn't support unicode... so we're gonna use Json.escape instead.
Fixes #114
> Fix JSON unicode string

- server/src/RescriptEditorSupport.ts
The analysis shouldn't throw, nor should JSON.parse. We don't wanna swallow them silently for now.
Now they'll throw; language-server shows an alert when things throw too much. We'll see how to proceed afterward.
But it's better than failing silently right now.
> Remove try catch around calling analysis binary

- analysis/src/Cli.ml
- analysis/src/Commands.ml
- analysis/src/References.ml
- analysis/src/State.ml
- analysis/tests/src/References.res
- analysis/tests/src/expected/References.res.txt
> Add a command to find all the references to an item.

- CHANGELOG.md
- analysis/src/NewCompletions.ml
- analysis/src/Protocol.ml
- analysis/tests/src/expected/Complete.res.txt
- analysis/tests/src/expected/Jsx.res.txt
> Remove url display from autocomplete popup

- analysis/src/PartialParser.ml
- analysis/tests/src/Jsx.res
- analysis/tests/src/expected/Jsx.res.txt
The autocomplete command does not support this yet, as the example shows.
https://github.com/rescript-lang/rescript-vscode/issues/147
> Add autocomplete of JSX props without test letter.

- analysis/src/Commands.ml
- analysis/src/Uri2.ml
- analysis/test.sh
- analysis/tests/src/Jsx.res
- analysis/tests/src/Jsx.resi
- analysis/tests/src/expected/Jsx.res.txt
- analysis/tests/src/expected/Jsx.resi.txt
See https://github.com/rescript-lang/rescript-vscode/issues/153
> Add tests showing hover on components not working in interface files.

- .github/workflows/ci.yml
- CONTRIBUTING.md
- analysis/Makefile
- analysis/README.md
- analysis/src/Cli.ml
- analysis/test.sh
- server/analysis_binaries/README.md
- server/src/constants.ts
This is so that in activity monitor and other places, they look idiomatic and debuggable
> Try a better prod binary name

- analysis/Makefile
- analysis/tests/package-lock.json
- analysis/tests/package.json
This was done in a1074e150bc3918e336c32df9ec5f3f0f9d2539a but lost in a4236375a56ffb637846ad43f8f297c874e7e456
Fixes #126.
Since no-op build is cheap, I took the occasion to simplify the makefile incrementalism (which was kinda wrong before too). Gotta love perf + full build.
> Re-bump rescript version; simplify makefile

- server/src/constants.ts
- server/src/server.ts
- server/src/utils.ts
> Use `rescript` to build when available

- analysis/src/Commands.ml
- analysis/src/Hover.ml
- analysis/src/ProcessCmt.ml
- analysis/src/References.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/A.res.txt
- analysis/tests/src/expected/Hover.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/178
> Towards better treatment of modules and module types.

- analysis/src/Packages.ml
> Fix possible infinite loop when `bsconfig.json` is not found.

- analysis/src/Commands.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Hover.res.txt
This makes it so that we get to format the file and all
> Fix test warning; allow indented test comment marker

- analysis/.depend
- analysis/src/BuildSystem.ml
- analysis/src/Files.ml
- analysis/src/FindFiles.ml
- analysis/src/Infix.ml
- analysis/src/ModuleResolution.ml
- analysis/src/Packages.ml
- analysis/src/Uri2.ml
Reverts rescript-lang/rescript-vscode#197
This is breaking jumpt-to-definition within the same file.
> Revert "Test using normal filename concat without trying to normalize `./foo`."

- analysis/src/Commands.ml
- analysis/src/ProcessCmt.ml
- analysis/src/References.ml
- analysis/tests/src/expected/A.res.txt
- analysis/tests/src/expected/Jsx.resi.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/204
> Add support for detailed info (jump-to-def, hover) on a signature.

- CHANGELOG.md
- analysis/src/PartialParser.ml
- analysis/tests/src/Jsx.res
- analysis/tests/src/expected/Jsx.res.txt
See https://github.com/rescript-lang/rescript-vscode/issues/213
> JSX Autocomplete: handle more cases of atomic expression  to the rhs of `=` without braces (variant, polymorphic variant, function call, etc)

- CHANGELOG.md
- analysis/src/ProcessCmt.ml
- analysis/tests/src/RecModules.res
- analysis/tests/src/expected/RecModules.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/194
> Add support for recursive modules.

- analysis/src/Hover.ml
- analysis/src/References.ml
- analysis/tests/src/expected/Hover.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/195
> Add support for transitive module references.

- client/package-lock.json
- client/package.json
- package-lock.json
- package.json
- server/src/server.ts
vscode-languageclient contains a different dep on vscode-jsonrpc. If we don't isolate the vscode-languageclient, server/src/server.ts might accidentally use it instead of its own vscode-jsonrpc
This fixes the problem of carrying the server into other editors
cc @ryyppy
> Isolate vscode-languageclient dependency back into client/

- server/src/utils.ts
This is based on lsp spec.
Some clients won't work with file paths (including neovim's built in lsp client).
> Fix using path as uri for diagnostics

- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Hover.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/180.
> Add test for component aliasing.

- analysis/src/Commands.ml
- analysis/src/NewCompletions.ml
Checking completion context is a simple text parse.
Only if this is successful, trigger complex cmt processing.
> Completion: for perf reasons first check completion context.

- analysis/src/NewCompletions.ml
- analysis/src/Packages.ml
- analysis/src/ProcessCmt.ml
- analysis/src/References.ml
- analysis/src/SharedTypes.ml
Files can be processes in different orders on different architectures because of how their layout on disk.
Add determinism by using sets instead of lists.
> Add determinism to processing of files.

- analysis/.depend
- analysis/src/Cli.ml
- analysis/src/Commands.ml
- analysis/src/References.ml
- analysis/tests/src/Cross.res
- analysis/tests/src/TypeDefinition.res
- analysis/tests/src/expected/Cross.res.txt
- analysis/tests/src/expected/TypeDefinition.res.txt
- server/src/server.ts
> Add type definition

- CHANGELOG.md
- package.json
This reverts commit ffdd918830e07766b8d2fdf796096d5d4f0907f8.
This check is already in place:
> Revert "Temporarily disable interface creation"

- CHANGELOG.md
- analysis/src/NewCompletions.ml
- analysis/tests/src/Jsx.res
- analysis/tests/src/expected/Jsx.res.txt
…rnal.
See https://github.com/rescript-lang/rescript-vscode/issues/307
When a component is declared as external, its type is different. Instead of being a function type, it is a type `React.componentLike` (which internally is defined as a function).
The treatment of JSX autocomplete does not currently recognise that type.
> Fix issue in JSX autocomplete when the component is declared external.

- CHANGELOG.md
- analysis/src/NewCompletions.ml
- analysis/src/PartialParser.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
- server/src/server.ts
Currently only covers the case of simple variable 'foo' accessed a `foo["...`
> Add autocompletion for object access of the form foo["bar"]

- CHANGELOG.md
- analysis/src/PartialParser.ml
- analysis/tests/src/Jsx.res
- analysis/tests/src/expected/Jsx.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/313
> Fix issue with JSX autocompletion not working after `foo=#variant`.

- CHANGELOG.md
- analysis/src/NewCompletions.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
The current function to extract record types looks for a type definition, and expect it to be a record.
The new one keeps on expanding type definitions until it finds a record. In this way, it handles type aliases.
Fixes https://github.com/rescript-lang/rescript-vscode/issues/311
> New function to extract record type.

- CHANGELOG.md
- analysis/src/ProcessCmt.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/323
The computation of scope for a struct/signatures takes the first and last items, ignoring the fact that they could be ghost locations.
In particular, using `@react.component` triggers the ppx which leaves ghost definitions at the end, making the end scope wrong.
> Fix issue in the calculation of struct/signature scopes.

- client/src/commands.ts
- client/src/commands/dead_code_analysis.ts
- client/src/extension.ts
- package.json
- server/src/server.ts
This implements a "Dead code analysis mode". When activated, the extension will run reanalyze continuously as the ReScript compiler runs, and report back any errors found directly into the editor. It'll also set up code actions leveraging the suggestions reanalyze gives for how to suppress the issues reported.
See the video below for more details.
https://user-images.githubusercontent.com/1457626/147784733-4eabe71f-7b20-441b-a9b7-bedda07b4d4e.mp4
Thank you @cristianoc for guidance both around reanalyze and details around how the extension does things.
Happy to hear any feedback or comments, and whether this is something you're interested in merging.
> Dead code analysis editor mode via reanalyze

- grammars/rescript.tmLanguage.json
should fix #324:
```res
let regex = `\``
let foo = 10
```
Should I first create a PR in [rescript-lang/rescript-sublime](https://github.com/rescript-lang/rescript-sublime)?
> Fix escaped backtick highlighting in string literal (#324)

- README.md
cc @ryyppy @cristianoc 
I added a whole new section etc. Let me know if this is too much and you'd like this structured in another way.
> Readme for the dead code analysis mode

- CHANGELOG.md
- server/src/utils.ts
Fixes https://github.com/rescript-lang/rescript-vscode/issues/305
> Don't crash when the binary command returns a large json.

- CHANGELOG.md
- server/src/utils.ts
When there's a self cycle, the compiler.log gives an (out-of-spec) error of the form:
```
FAILED: Tst has a self cycle
```
Notice the compiler is silent when the cycle involves more than one file (the terminal shows an error, but compiler.log is empty).
> Don't crash when the file has a self cycle.

- CHANGELOG.md
- grammars/rescript.tmLanguage.json
Fix issue with highlighting of templates introduced in https://github.com/rescript-lang/rescript-vscode/pull/325
and reported in
https://github.com/rescript-lang/rescript-vscode/issues/345
> Fix issue with highlighting of templates.

- CHANGELOG.md
- analysis/src/ProcessCmt.ml
- analysis/tests/src/LongIdentTest.res
- analysis/tests/src/TableclothMap.ml
- analysis/tests/src/TableclothMap.mli
- analysis/tests/src/expected/Debug.res.txt
- analysis/tests/src/expected/LongIdentTest.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/350
Lonident applications in types are only possible in ml, not in rescript. They might show up in the AST with OCaml dependencies.
> Don't crash on hover when a dependency contains lident application.

- server/src/server.ts
- server/src/utils.ts
I found out that the compiler appends `-MyNamespace` to `cmi` file names if the `"namespace"` attribute is set in `bsconfig.json`. This case is now handled correctly by the `create-interface` command.
> Fix creating interface files for namespaced packages

- CHANGELOG.md
- analysis/src/Cmt.ml
- analysis/src/Commands.ml
- analysis/src/Hover.ml
- analysis/src/NewCompletions.ml
- analysis/src/Packages.ml
- analysis/src/PartialParser.ml
- analysis/src/ProcessAttributes.ml
- analysis/src/ProcessCmt.ml
- analysis/src/References.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/Obj.res
- analysis/tests/src/expected/Completion.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/360
> Support autocomplete for objects from another module `M.x[...`.

- client/src/commands.ts
- client/src/commands/create_interface.ts
- client/src/commands/open_compiled.ts
- client/src/extension.ts
- package.json
- server/src/constants.ts
- server/src/server.ts
- server/src/utils.ts
This implements #107 
Press CMD+Shift+P and select `ReScript: Open the compiled JS file for this implementation file.`
It should open the corresponding `.bs.js`, `.js`, `.mjs` in the correct directory (whether in-source or not).
Unfortunately, this requires to parse `bsconfig.json`. I did not know how to account for an array with more than one element of package-specs, so for now it just takes the first one, but I guess it is better to use an object anyway, as [suggested by the docs](https://rescript-lang.org/docs/manual/latest/build-configuration#package-specs).
> Command to open compiled file

- client/src/commands/dead_code_analysis.ts
- package.json
- Expose the "Stop dead code analysis" command to the user so it can be run via the command palette. We already have the start command exposed, so I think it makes sense to expose the stop command as well, in addition to the stop button in the status bar.
- Do not mark "redundant optional argument" warnings as dead/unused code, since it's not really. Closes https://github.com/rescript-lang/rescript-vscode/issues/362
> Dce touchups

- server/src/utils.ts
Closes https://github.com/rescript-lang/rescript-vscode/issues/245
> detect warnings configured as errors

- .github/workflows/ci.yml
I thought this would be useful for testing, since it makes it easier for everybody to just download and install the VSIX directly after any master or PR build.
This adds about half a minute of build time.
> Add GH action to package VSIX file for testing

- CHANGELOG.md
- analysis/src/Cli.ml
- analysis/src/Commands.ml
- server/src/server.ts
- server/src/utils.ts
This lifts the current requirement for files to be located in an actual ReScript project to be formatted. It falls back to formatting using the vendored parser pretty printer in the extension itself if the file isn't located in a ReScript project.
> relax requirement of files being in a ReScript project for formatting

- grammars/rescript.tmLanguage.json
As discussed in #380, this PR restores some grammar that got cleaned up in https://github.com/rescript-lang/rescript-vscode/commit/0e56b5e9f061ef06921e5fbde64590fecf77ec9b and https://github.com/rescript-lang/rescript-vscode/commit/dd9c37566522df7ca137f82798c489518309c312.
Here's how it looks with this PR (semantic highlighting on the right for comparison):
> Restore some modules and JSX grammar

- server/src/server.ts
Fixes https://github.com/rescript-lang/rescript-vscode/issues/392
> Fix issue with crash on rename.

- analysis/src/Completion.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
The scope mechanism was missing a number of cases for complex patterns, as well as cases in switches.
> Fix issue where variables bound in switches were not be completed.

- analysis/src/NewCompletions.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Debug.res.txt
- server/src/server.ts
Pervasives can lead to very noisy autocompletion.
Don't use values from Pervasives by default.
Can be explicitly triggered by `Pervasives.`.
> Do not complete from Pervasives by default.

- analysis/src/Completion.ml
- analysis/src/Utils.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/Jsx.res
- analysis/tests/src/RecordCompletion.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Div.res.txt
- analysis/tests/src/expected/Jsx.res.txt
- analysis/tests/src/expected/RecordCompletion.res.txt
Since the parser allows space after ".", some autocomplete user intent can get lost.
For example:
```
type record = {
someProp: SomeModule. // <-- cursor
otherProp: string,
}
```
The parser will parse as `SomeModule.otherProp` then error on the ":" token.
The autocomplete engine now recognises these situations and splits up `SomeModule.otherProp`, which is provided by the parser's AST, into `SomeModule.`.
> Cut an identifier at blank/space after dot.

- analysis/src/Commands.ml
- analysis/src/Completion.ml
- analysis/src/NewCompletions.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
Instead of requiring the lhs to be a long identifier, now allow a generic context.
E.g. `funRecord.someFun(~ )`
> Generalize named argument completion

- analysis/src/Commands.ml
- analysis/src/Completion.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
Sometime the parser gets confused while parsing the expr assigned to a prop in `prop = expr`.
In that case the location of `expr` might end into a dummy location when the parser inserts a "rescript.exprhole".
What that happens, don't do label completion to be on the safe side.
> Fix issue with error recovery during label completions.

- README.md
- grammars/rescript.tmLanguage.json
- package.json
- server/src/server.ts
Instead of semantic token `type` use `support.type.primitive` from the grammar. This is what TypeScript does too.
For keywords from the grammar, use `storage.type` instead of `keyword`. Again this is taken from what TS does.
This change is a no-op on the themes considered so far. But improves theme `Solarized Light` and `One Dark Pro`.
Remove `Mariana Pro (Warm)` from the list of recommended themes, as it seems to disable semantic highlighting entirely.
Looks like TS has the same problem there.
> Syntax highlighting: support more themes.

- analysis/src/ProcessCmt.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Fragment.res.txt
- analysis/tests/src/expected/Hover.res.txt
See https://github.com/rescript-lang/rescript-vscode/issues/302
> Fix issue of poly variant duplication.

- analysis/src/CompletionFrontEnd.ml
- analysis/src/vendor/res_outcome_printer/res_core.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Jsx.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/416
See https://github.com/rescript-lang/syntax/pull/491
> Fix issue with completion inside template expression.

- server/src/server.ts
More robust solution where the file cache is set also for files with extension not `.res` or `.resi`.
In case of rename e.g. from `.res` to `.rex` an opened file notification is sent for the `.rex` file and a crash happens when trying to get the current file content.
After this change, the file content array is set also for the .rex` file, preventing the crash.
Fixes https://github.com/rescript-lang/rescript-vscode/issues/392
> Fix extension crash when renaming a file.

- README.md
- client/src/extension.ts
- package.json
- server/src/constants.ts
- server/src/server.ts
Fixes https://github.com/rescript-lang/rescript-vscode/issues/23
This introduces configuration in the extension, periodically synced to the language server for use. We'll probably need to revisit this if we get more intricate configuration needs later on, but for now this is simple enough and will do for the cases we currently have.
> sharing config between client and server

- client/src/extension.ts
Initial read configuration was never refreshed as the restart command runs, which means you'd always get potentially stale initial config after a restart.
Also clean up a few init things that I suspect has never been cleaned up after the initial adaption of the LS client example.
> ensure updated config is synced on use of restart command

- analysis/src/Cli.ml
- analysis/src/Commands.ml
- analysis/src/References.ml
- analysis/src/Xform.ml
- analysis/tests/package-lock.json
- analysis/tests/package.json
- analysis/tests/src/expected/Div.res.txt
- analysis/tests/src/expected/Fragment.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/Jsx.res.txt
- analysis/tests/src/expected/Jsx.resi.txt
There are a number of heuristics when getting a loc item from a text position.
These heuristics are related to the behaviours of the JSX ppx and internal compiler behaviours that leak into the position of elements.
> Investigate heuristics in jump to location.

- CHANGELOG.md
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/RecordCompletion.res.txt
- analysis/vendor/res_outcome_printer/res_ast_conversion.ml
- analysis/vendor/res_outcome_printer/res_ast_debugger.ml
- analysis/vendor/res_outcome_printer/res_comments_table.ml
- analysis/vendor/res_outcome_printer/res_core.ml
- analysis/vendor/res_outcome_printer/res_driver_reason_binary.mli
- analysis/vendor/res_outcome_printer/res_grammar.ml
- analysis/vendor/res_outcome_printer/res_multi_printer.ml
- analysis/vendor/res_outcome_printer/res_multi_printer.mli
- analysis/vendor/res_outcome_printer/res_outcome_printer.ml
- analysis/vendor/res_outcome_printer/res_parens.ml
- analysis/vendor/res_outcome_printer/res_parser.ml
- analysis/vendor/res_outcome_printer/res_parser.mli
- analysis/vendor/res_outcome_printer/res_parsetree_viewer.ml
- analysis/vendor/res_outcome_printer/res_parsetree_viewer.mli
- analysis/vendor/res_outcome_printer/res_printer.ml
- analysis/vendor/res_outcome_printer/res_scanner.ml
- analysis/vendor/res_outcome_printer/res_token.ml
- analysis/vendor/res_outcome_printer/res_utf8.ml
- analysis/vendor/res_outcome_printer/res_utf8.mli
Fixes https://github.com/rescript-lang/rescript-vscode/issues/454
This commit: https://github.com/rescript-lang/syntax/commit/3aec2c85b8283eb7b632fb19f06048fa1540daa0
> Sync parser and outcome printer from syntax master

- client/src/commands/code_analysis.ts
So we don't accidentally crash the extension if we don't get proper json from reanalyze. It happens locally for me, which is another issue I'll investigate. But, this will at least ensure we don't crash.
> null check reanalyze output

- client/package-lock.json
- client/package.json
- client/src/extension.ts
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- server/src/server.ts
This upgrades all LSP related packages to their latest versions. Unblocks further progress on https://github.com/rescript-lang/rescript-vscode/pull/457 and https://github.com/rescript-lang/rescript-vscode/pull/453.
> Upgrade LSP related packages

- analysis/src/CompletionFrontEnd.ml
Observed this during interactive editing.
The command received an offset that does not belong to the current file being edited.
> Fix crash where the completion command receives a non-existing offset.

- client/package-lock.json
- client/package.json
Fixes https://github.com/rescript-lang/rescript-vscode/issues/474
This updates `vscode-languageclient` to the latest version, fixing a bug introduced when upgrading from v7 to v8 of that package. The bug was that the event for content in the editor being updated would arrive _after_ the request for formatting or completion. This caused bugs in both formatting and completion where the respective commands would operate on stale content if the commands ran fast enough, before the event signaling that the editor content had changed had time to dispatch.
> upgrade vscode-languageclient

- server/src/server.ts
- server/src/utils.ts
Fixes https://github.com/rescript-lang/rescript-vscode/issues/477
Problems tab was accidentally being cleared because the logic handling syntax error diagnostics did not account for pre-existing compiler errors.
> fix problem tab accidentally being cleared

- package.json
- server/src/constants.ts
- server/src/server.ts
- server/src/utils.ts
This PR fixes #412 .
I added the handling of the relative path and also the path with contains the home directory symbol. But I'm not sure that it is ok.
> The path option was added to the rescript.settings

- server/src/server.ts
Using `rescritls` on Neovim client with following configuration raise a error.
```lua
require'lspconfig'.rescriptls.setup = {
cmd = {
'node',
'/home/pedro/Desktop/Projects/rescript-vscode/server/out/server.js',
'--stdio',
},
init_options = {
extensionConfiguration = {
askToStartBuild = false,
},
},
}
```
Steps to reproduce:
1. Open a project
2. Open `.res` file
LSP Log:
```
[START][2022-07-21 17:02:07] LSP logging initiated
[ERROR][2022-07-21 17:02:08] .../vim/lsp/rpc.lua:420	"rpc"	"node"	"stderr"	"/home/pedro/Desktop/Projects/rescript-vscode/server/out/server.js:805\n                    extensionConfiguration.binaryPath[0] === \"~\") {\n                                                     ^\n\nTypeError: Cannot read property '0' of undefined\n    at StreamMessageReader.onMessage [as …
```
> Neovim: fix binary path

- analysis/src/FindFiles.ml
Fixes #506. 
In commit 4f072736099fa8842f05643b289de005f9193bdb the `nameSpaceToName` call did not survive a refactoring. I brought it back with this PR.
> Fix missing nameSpaceToName call

- .github/workflows/ci.yml
This fixes the commit SHA used for the VSIX artifact name in PR builds.
Now it matches the last commit in the PR (9fe9e91 in this case).
> Fix commit SHA in artifact name for PR builds

- .github/workflows/bump-version.js
- .github/workflows/ci.yml
- package-lock.json
- package.json
~~This is a first step to having automatic pre-releases published in the VSCode marketplace.~~
Somebody with access rights needs to create a `secrets` environment in this GitHub repository and add (one of) the ReScript team's [Personal Access Token (PAT)](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) as an environment variable, named  `MARKETPLACE_TOKEN `.
EDIT: 
This PR is basically done, but there is probably still room for some fine-tuning. As mentioned above, someone with write access needs to provide the token(s). 
Also the `chenglou92.rescript-vscode` needs to be updated to whatever will be the VSCode publisher name afterwards.
> Add vsce pre-release step to CI

- analysis/src/SemanticTokens.ml
> add `Pstr_primitive` to semanticTokens

- analysis/vendor/res_outcome_printer/res_core.ml
- analysis/vendor/res_outcome_printer/res_grammar.ml
- analysis/vendor/res_outcome_printer/res_parens.ml
- analysis/vendor/res_outcome_printer/res_parens.mli
- analysis/vendor/res_outcome_printer/res_parsetree_viewer.ml
- analysis/vendor/res_outcome_printer/res_parsetree_viewer.mli
- analysis/vendor/res_outcome_printer/res_printer.ml
- analysis/vendor/res_outcome_printer/res_printer.mli
- analysis/vendor/res_outcome_printer/res_token.ml
So that async/await etc is properly supported.
This is a bit ahead of time w.r.t. releases but should not hurt uses with the current compiler.
> Vendor latest parser/printer.

- server/src/server.ts
When then `inlayHints.enable` is not in `initializationOptions`
LSP Log:
```
[ERROR][2022-07-26 17:34:09] .../vim/lsp/rpc.lua:420	"rpc"	"node"	"stderr"	"/home/pedro/Desktop/Projects/rescript-vscode/server/out/server.js:839\n                    inlayHintProvider: extensionConfiguration.inlayHints.enable,\n                                                                         ^\n\nTypeError: Cannot read property 'enable' of undefined\n    at StreamMessageReader.onMessage [as callback] (/home/pedro/Desktop/Projects/rescript-vscode/server/out/server.js:839:74)\n    at /home/pedro/Desktop/Projects/rescript-vscode/server/node_modules/vscode-jsonrpc/lib/common/messageReader.js:162:26\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n"
```
> fix undefined inlayHints

- package.json
The setting is called `rescript.settings.codeLens` instead of `rescript.settings.codeLens.enable`.
> Remove ".enable" from rescript.settings.codeLens in package.json

- server/src/constants.ts
- server/src/server.ts
This should fix #514 and also will make formatting faster (at least on windows).
Supersedes #521 
I refactored the binary lookup a bit so that:
* we do not need to call existsSync twice on the same file
* the function returns the binary path itself
When no binaryPath is set, the extension will lookup and use the `bsc.exe` now (again).
Also the message when no binary has been found could have shown null as path. I simplified it for that case.
Edit: Fixes #530 now as well.
> Call bsc.exe directly, when no binaryPath is set in settings

- CHANGELOG.md
- analysis/src/Commands.ml
- analysis/src/Hint.ml
- analysis/tests/src/InlayHint.res
- analysis/tests/src/expected/InlayHint.res.txt
> Inlay Hints: better support for destructuring

- client/src/commands.ts
- client/src/commands/code_analysis.ts
- client/src/extension.ts
Follow up for: https://github.com/rescript-lang/rescript-vscode/issues/537
This logs a more elaborate error for the user, including instructions on how to report the error, when reanalyze json is invalid for some reason.
> More elaborate error message for users on reanalyze json error

- analysis/src/Files.ml
- analysis/src/Hint.ml
- analysis/src/SemanticTokens.ml
- analysis/src/Xform.ml
This is a continuation of https://github.com/rescript-lang/rescript-vscode/pull/539
> Checking if a file is a res file

- analysis/src/FindFiles.ml
Apparently, `Json.bool` returns `None` when the value is there but not a boolean.
> Fix isNamespaced check when namespace is string

- server/src/constants.ts
- server/src/server.ts
> Fix formatter not being available for macOS ARM with ReScript <= 9.1.4

- client/src/extension.ts
- package.json
- server/src/server.ts
- server/src/utils.ts
This adds a setting for explicitly allowing the use of the built in formatter when trying to format a ReScript file that's not strictly part of a ReScript project. Whenever a user tries to format a file where the ReScript compiler can't be found, the user will be prompted that explicit permissions are needed, together with a link to that specific setting.
Closes https://github.com/rescript-lang/rescript-vscode/issues/556
> prompt user to explicitly allow formatting using the built in formatter

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Hover.res.txt
See https://github.com/rescript-lang/rescript-vscode/issues/349
> Support type instantiation during autocompletion.

- .github/workflows/ci.yml
- server/src/constants.ts
This adds the rescript-editor-analysis.exe binary for macOS ARM.
> Add macos-arm binary

- .github/workflows/ci.yml
See https://github.com/actions/runner-images/issues/6002.
> Use the ubuntu-20.04 runner as 18.04 is deprecated

- CHANGELOG.md
- analysis/reanalyze/src/Paths.ml
Fixes https://github.com/rescript-lang/rescript-vscode/issues/574
> Fix issue with logging not in debug mode.

- .github/workflows/ci.yml
This was due to consolidating the get-version-number and increment-version-number steps in the previous PR. The JSON string was probably converted automatically in between to a raw string.
> Use raw string instead of JSON for bump-version parameter

- server/src/server.ts
- server/src/utils.ts
...including instructions on how to report the issue.
> prompt the user whenever parsing errors/warning from the compiler log fails

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/JsxV4.res
- analysis/tests/src/expected/JsxV4.res.txt
https://github.com/rescript-lang/rescript-compiler/issues/5406
> Add support for prop completion for JSX V4

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/src/Shared.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Auto.res.txt
- analysis/tests/src/expected/Definition.res.txt
- analysis/tests/src/expected/Div.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/vendor/compiler-libs-406/printtyp.ml
Fixes https://github.com/rescript-lang/rescript-vscode/issues/557
> Expand one level of type definition on hover and fix optional field type.

- analysis/src/Commands.ml
- analysis/src/Hover.ml
- analysis/src/Markdown.ml
- analysis/src/Shared.ml
- analysis/src/Uri.ml
- analysis/src/Uri.mli
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Hover.res.txt
Closes https://github.com/rescript-lang/rescript-vscode/issues/588
This refactors the recently introduced type expansion in hovers to be easily reusable for other purposes.
It then applies that same type expansion on the hover contents produced when the hover is done via the autocomplete functionality.
https://github.com/rescript-lang/rescript-vscode/commit/825afc253c9c1e93842890c9743abde83746dc19 this commit is probably the most relevant one, showing how this changes what's produced when hovering something unsaved but where we can still find a type to show via autocomplete.
> Expand types on autocomplete hover

- .github/workflows/ci.yml
Recently, CI builds have been logging warnings like this:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/cache, actions/upload-artifact, actions/cache, actions/checkoutShow less
Upgrade all actions to the latest major versions to fix this.
Also use node 16 everywhere (we had 14 in one place and 16 in another).
> Upgrade Github actions versions to fix deprecation warnings

- analysis/src/CompletionBackEnd.ml
- analysis/src/Packages.ml
- analysis/src/SharedTypes.ml
- Prefers the new stdlib, if available, for pipe completion
- Adds pipe completion for more builtins
> complete builtins from the new stdlib if availabile

- CHANGELOG.md
- analysis/src/CreateInterface.ml
- analysis/tests/src/JsxV4.res
Fixes https://github.com/rescript-lang/rescript-vscode/issues/617
> Adapt command to create interface files to latest JSX V4

- analysis/src/SignatureHelp.ml
- analysis/tests/src/SignatureHelp.res
- analysis/tests/src/expected/SignatureHelp.res.txt
Previously, the signature help wouldn't understand pipes, meaning signature help for piped expressions would always be off by one when having unlabelled arguments. This diff fixes the signature help to account for pipes when present.
Closes https://github.com/rescript-lang/rescript-vscode/issues/618
> Signature help - handle pipes

- CHANGELOG.md
- analysis/src/DocumentSymbol.ml
- analysis/src/Protocol.ml
- analysis/tests/src/expected/DocumentSymbol.res.txt
Change response format to [documentSymbol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol). [symbolInformation](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolInformation) are deprecated.
Close #628
> fix: document symbol path location

- CHANGELOG.md
- client/src/commands/create_interface.ts
- client/src/commands/open_compiled.ts
- server/src/server.ts
- server/src/utils.ts
I was writing some handlers in Neovim for `createInterface` and `openCompiled`. Methods names use the same format to register commands in vscode e.g `rescript-vscode.open_compiled`
Rename methods names, following LSP spec:
- `rescript-vscode.open_compiled` => `textDocument/openCompiled`
- `rescript-vscode.create_interface` => `textDocument/createInterface`
Response changes:
- `textDocument/openCompiled` now return uri file scheme
- `textDocument/createInterface` now return the path of the file, so that I can open the file after creation
> custom LSP requests

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/src/ProcessCmt.ml
- analysis/src/References.ml
- analysis/src/ResolvePath.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/expected/Hover.res.txt
> fix: Incorrect type hint for module type

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/src/Protocol.ml
- analysis/tests/src/expected/Auto.res.txt
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Definition.res.txt
- analysis/tests/src/expected/Div.res.txt
- analysis/tests/src/expected/DocComments.res.txt
- analysis/tests/src/expected/Fragment.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/Jsx2.res.txt
- analysis/tests/src/expected/Jsx2.resi.txt
- analysis/tests/src/expected/JsxV4.res.txt
- analysis/tests/src/expected/LongIdentTest.res.txt
- analysis/tests/src/expected/RecModules.res.txt
**Before:**
Neovim LSP builtin:
VSCode:
**After:**
Neovim:
VSCode:
> hover: remove spacing between type definition 

- CHANGELOG.md
- analysis/src/CreateInterface.ml
- analysis/tests/src/JsxV4.res
- analysis/tests/src/expected/JsxV4.res.txt
See https://github.com/rescript-lang/rescript-vscode/issues/617
> Fix issue where create interface file does not work with V4

- CHANGELOG.md
- analysis/src/Cmt.ml
- analysis/src/Commands.ml
- analysis/src/Hint.ml
- analysis/src/Hover.ml
- analysis/src/SignatureHelp.ml
- analysis/src/Xform.ml
- analysis/tests/src/expected/InlayHint.res.txt
- It was calling `Cmt.fullFromPath` for each hint.
- Removes inlay hints for parameters. It's not necessary as code lenses already do this job.
A noticeable change to `analysis/examples/large-project/src/res_core.res`
Is there any way to measure?
Part of #511
cc @zth
> Polish: inlay hints and codelens performance

- CHANGELOG.md
- analysis/src/Utils.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
Added the failing test mentioned in #643
The funny thing is, I tried to change the `Js.log("Hello")` to a `()` which made the second completion work as well. No idea what's going on there.
> Add failing completion test

- CHANGELOG.md
- analysis/src/Commands.ml
- analysis/src/ProcessCmt.ml
- analysis/tests/src/References.res
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/References.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/645
References to elements defined in an interface file are not working. E.g.
```res
module M: {
let aa: int
} = {
let aa = 10
}
let bb = M.aa
let cc = bb
let dd = M.aa
//          ^ref
```
The observed issue is that the locations of the references are fine, but the location of the definition in the module type is reported as being a ghost location (line -1).
This PR simply removes the ghost location from the results. Still need to look at why such ghost location is produced (go to definitions goes to the correct location in the module type).
For components, the JSX ppx produces 2 values called `make` shadowing one another, which triggers the compiler to generate a module constraint with a module type having only one `make`, …
> Fix issue with references to elements defined in an interface file

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/src/ProcessCmt.ml
- analysis/src/References.ml
- analysis/src/ResolvePath.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Cross.res
- analysis/tests/src/DefinitionWithInterface.res
- analysis/tests/src/DefinitionWithInterface.resi
- analysis/tests/src/expected/Cross.res.txt
- analysis/tests/src/expected/DefinitionWithInterface.res.txt
- analysis/tests/src/expected/DefinitionWithInterface.resi.txt
In the example, the reference to `DefinitionWithInterface.Inner.y` leads to `DefinitionWithInterface.y` instead. This seems to happen only when there is an interface file, and the outer module has the same value named `y` as the inner module.
See https://github.com/rescript-lang/rescript-vscode/issues/652
> Fix issue where jump to definition would go to the wrong place when there are aliased identifiers in submodules

- CHANGELOG.md
- analysis/src/DocumentSymbol.ml
- analysis/src/Protocol.ml
- analysis/tests/src/expected/DocumentSymbol.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/654.
The change in https://github.com/rescript-lang/rescript-vscode/pull/629 moved to a non-deprecated representation of document symbols. The new representation is the "Ikea" version of the old one, where children symbols are not computed for you, but need to be provided. This PR computes and emits the tree of symbols using the `children` field.
> Emit nested document symbols.

- README.md
- analysis/src/Commands.ml
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/Hover.ml
- analysis/src/SharedTypes.ml
- analysis/src/SignatureHelp.ml
- analysis/tests/src/CompletionPipeChain.res
- analysis/tests/src/expected/CompletionPipeChain.res.txt
This fixes pipe completion for functions returning a type not known until the code has compiled. `Array.reduce` being an example, which has the signature `('a, ('a, 'b) => 'a) => 'a`. It returns `'a` but we don't know what `'a` is unless it has compiled.
This makes it so that this now completes as `int` (after saving):
```
let _ = [123]->Belt.Array.reduce(0, (acc, curr) => acc + curr)->
```
Again, note this only has effect _after saving_ (compiling so that the type parameter is instantiated). But it at least enables pipe completion in this scenario, even if it requires saving, which used to not work at all.
> Pipe completion unknown/type parameter return types

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionPipeSubmodules.res
- analysis/tests/src/expected/CompletionPipeSubmodules.res.txt
Before this, a type path of non-zero length was assumed to come from the compiler, otherwise the path of the completion environment was taken verbatim.
Neither case is correct.
Now there's a single case, where one takes into account 2 inputs:
- the current environment which gives context to the type path
-  the type path, which is interpreted as starting within that environment
Since submodules can refer to types into other submodules, the path needs to be resolved to determine the actual path starting from the root of the file. This requires keeping track of where a module is defined. It could be defined in the current env, or in a parent one. The current env is walked backwards toward the root until the required module is found, and the resulting paths combined.
> Make pipe completion work reliably across submodules.

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
Completes `int` and `float` constants.
> Pipe complete more builtins

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/BrokenParserCases.res
- analysis/tests/src/CompletionFunctionArguments.res
- analysis/tests/src/expected/BrokenParserCases.res.txt
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- server/src/server.ts
The first in likely a long series of PRs bringing in and refining the work done in https://github.com/rescript-lang/rescript-vscode/pull/493, but little bit by bit.
This PR does the following:
- Completes the expressions of labelled arguments or unlabelled arguments in function applications.
- Currently completes booleans, options and variants. The rest of the relevant types (polyvariants, records, tuples, etc) will be completable as well in due time.
There are caveats that I've added comments for in the PR.
The next step will be getting support for snippets in completion items in, so we can intelligently move the cursor for the user into payloads of constructors etc. That'll come in a separate PR.
After that, completing polyvariants. 
Then the same work as in this PR, but for JSX props.
> Complete function argument values

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionJsxProps.res
- analysis/tests/src/CompletionSupport.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
- analysis/tests/src/expected/Jsx2.res.txt
This is ready for an initial review @cristianoc . A few things to consider:
* Can we figure out if we need to qualify variant constructors as we complete them? That's a typical issue with JSX props IIRC, that you almost always have to qualify them so the compiler can find them.
* How can we figure out if we need to expand options for JSX props? With fn arguments it was "easy" - optional label should expand option. How do we do it in JSX, do we need to look up the underlying make function? Maybe we already have access to what we need and I just need a gentle push in the right direction to connect the dots.
Closes https://github.com/rescript-lang/rescript-vscode/issues/322
> complete JSX prop values

- CHANGELOG.md
- analysis/src/Cfg.ml
- analysis/src/Cli.ml
- analysis/src/CompletionBackEnd.ml
- analysis/src/Protocol.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionFunctionArguments.res
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
- server/src/server.ts
This adds support for snippets in completion. Snippets lets us tell the editor where we want the cursor to move as the user tabs its way through the newly inserted text.
* Add snippet support
* Implement snippets for a few existing things like completion options, variant constructor arguments, etc
* Implement very basic completion for tuples, including with snippet support
> Completion snippet support

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionJsxProps.res
- analysis/tests/src/CompletionSupport.res
- analysis/tests/src/expected/CompletionJsxProps.res.txt
Continuing type based completion, this adds completion for polyvariants.
> Complete polyvariants

- CHANGELOG.md
- analysis/src/Packages.ml
Adjusts what modules we complete from when `Belt` is open.
> Adjust autocomplete when Belt is open

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SignatureHelp.ml
- analysis/src/Utils.ml
- analysis/tests/src/SignatureHelp.res
- analysis/tests/src/expected/SignatureHelp.res.txt
Better precision in signature help. You now don't have to start typing in an argument for it to highlight. We now look at commas to decide which argument you're currently intending to fill in.
Closes https://github.com/rescript-lang/rescript-vscode/issues/672
> Improve signature help precision

- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
Accidentally completes from Pervasives when it should complete from Belt.Result.
The resulting path we're completing from becomes `result.Pervasives`, when we're looking for just `result`. So the completion ends up being derived from `Pervasives`. 
What do you think is the best way to solve this @cristianoc?
> add broken completion case for result

- CHANGELOG.md
- analysis/src/SignatureHelp.ml
- analysis/tests/src/expected/SignatureHelp.res.txt
Cleans up the output some by getting rid of the redundant `let nameOfFn: ` part of what's shown to the end user.
> remove redundant function name from signature help output

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/BrokenParserCases.res
- analysis/tests/src/CompletionPattern.res
- analysis/tests/src/expected/BrokenParserCases.res.txt
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionPattern.res.txt
This isn't complete yet, but I want to validate the approach with you @cristianoc before I continue deeper. This PR does the following:
- Introduces the concept of pattern completion
- Adds logic for tracking what type we're at in the current pattern. Currently handles tuples and record fields, but will eventually handle everything that can appear in a pattern (like variant/polyvariant constructors + payloads, options, array literals, etc)
> Initial pattern completion

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
This is important because it's so common to switch on tuples of multiple variables/values.
> complete unsaved tuples

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/Protocol.ml
- analysis/src/SharedTypes.ml
- analysis/src/Utils.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/CompletionFunctionArguments.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
- analysis/tests/src/expected/CompletionPattern.res.txt
- analysis/tests/src/expected/Jsx2.res.txt
This extends the current expression completion to handle more cases (records, arrays, tuples, etc), and also handle nested expressions (record fields, constructor payloads, etc etc).
It's essentially a one-to-one port of the nested pattern completion, but for expressions instead.
After this lands, we can soon start refactoring and break up the giant CompletionFrontend/CompletionBackend a bit in my opinion.
> Nested expression completion

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/Utils.ml
- analysis/src/Xform.ml
- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/CompletionJsx.res.txt
Something I've wanted for a while. This will add `React.string`, `React.array` etc to the completion items for relevant types in pipe when in a JSX context. Being in a JSX context is defined as a) being in the body of a `make` function annotated with `@react.component`, or b) being inside of JSX.
Example:
Doing pipe completion on an `int` in JSX context will return `React.int` in the completion items, in addition to the builtin completions for `int`.
This accomplishes two things:
1. Convenience, since you otherwise have to first complete for `React`, and then the fn you're after.
2. Helps beginners with understanding that you in ReScript need to use the respective `React.element` producing functions in JSX.
> complete for functions creating React.element when in a JSX context

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionPattern.res.txt
This is a QoL thing to make working with options easier in typed completion, allowing you to skip a step completing inside of `Some` and directly have access to the possible `Some` values.
> expand options in typed expr/pattern completion

- server/src/server.ts
This workaround brings back semantic highlighting until the referenced PR in #686 gets merged.
> Fix semantic highlighting

- client/package-lock.json
- client/package.json
While we fixed #686 already with a little workaround, I think it's better not to use a broken version of the `vscode-languageserver-node` client.
> Upgrade client to fix some regressions

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionPattern.res
- analysis/tests/src/expected/CompletionPattern.res.txt
This makes it so that triggering completion on `_` (`Ppat_any`) is considered the same as triggering an empty typed completion. `Some(<com>)` and `Some(_<com>)` is now considered the same when triggering completion.
The main reason is that we're inserting `_` and putting the cursor on it via snippets. So, being able to trigger completion directly again on `_` is quite helpful.
> Let ppat_any trigger completion in patterns

- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionDecorators.ml
- analysis/src/CompletionExpressions.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/CompletionJsx.ml
- analysis/src/CompletionPatterns.ml
- analysis/src/CreateInterface.ml
- analysis/src/LocalTables.ml
- analysis/src/SignatureHelp.ml
- analysis/src/TypeUtils.ml
- analysis/src/Utils.ml
I've just moved things around and tried to move things into sub modules. Should hopefully make the code a bit more approachable. More can be done of course, but I think this is a good start.
> break up CompletionBackend and CompletionFrontend into modules

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/Protocol.ml
- analysis/src/SharedTypes.ml
- analysis/src/Utils.ml
- analysis/src/Xform.ml
- analysis/tests/src/ExhaustiveSwitch.res
- analysis/tests/src/expected/ExhaustiveSwitch.res.txt
- snippets.json
This is a proposal to solve https://github.com/rescript-lang/rescript-vscode/issues/253.
It's also the first step of https://github.com/rescript-lang/rescript-vscode/issues/684, moving snippets into the analysis bin and only outputting them where they make sense.
(this GIF isn't 100% accurate, I've done some cosmetic fixes to the completion list since recording it)
This PR does the following: When completing.. 
- an _ident_ after a _switch_
- and the switch has no cases
- and the type of the ident we're completing is something we can (reasonably) generate an exhaustive switch for
- ...add a separate completion item for the ident that, when chosen, inserts an exhaustive switch statement for that ident
Closes https://github.com/rescript-lang/rescript-vscode/issues/253
> implement exhaustive switch completion

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionPipeChain.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionPipeChain.res.txt
Pipe completion does not work on aliased types. Wondering what the best way would be to make it work.
> add broken test for pipe completion on aliased types

- analysis/src/CompletionBackEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/CompletionPattern.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionPattern.res.txt
- server/src/server.ts
This completes function snippets in positions where a function is expected. I think this is a cool feature that can be quite useful.
> complete function snippets

- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/Destructuring.res
- analysis/tests/src/expected/Destructuring.res.txt
Tests for #704.
The first two are working fine, the second two not.
> Add broken test for record destructuring

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/Utils.ml
- analysis/tests/src/CompletionJsxProps.res
- analysis/tests/src/expected/CompletionJsxProps.res.txt
Enables expression completion for lowercase JSX tags, aka builtins.
> typed expression completion for lowercase JSX tags

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/RecModules.res.txt
> Fix incorrect syntax in hover help for module

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/DumpAst.ml
- analysis/src/ProcessCmt.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/src/Utils.ml
- analysis/tests/src/CompletionTypeAnnotation.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- analysis/tests/src/expected/CompletionPattern.res.txt
- analysis/tests/src/expected/CompletionTypeAnnotation.res.txt
Completion via annotations. E.g: `let x: someVariant = O<com>` completes for the variant `someVariant`, even if the let assignment hasn't compiled previously.
Only handles "basic" types as of now. No handling of options etc.
Currently quite messy, but looking for your feedback before I continue @cristianoc .
> [WIP] Annotated completions

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Destructuring.res
- analysis/tests/src/expected/Destructuring.res.txt
Closes https://github.com/rescript-lang/rescript-vscode/issues/714
cc @cknitt
> special handling of optional fields when destructuring

- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/CompletionJsxProps.res
- analysis/tests/src/CompletionSupport.res
- analysis/tests/src/expected/CompletionJsxProps.res.txt
Didn't account for nested values when deciding when to insert braces for JSX prop values when completing.
> Fix jsx wrapping in completion

- analysis/src/CompletionJsx.ml
- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/CompletionJsx.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/707
A bit unsure if this is the best approach. What do you think @cristianoc ?
> enable completions for handwritten JSX components

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/Packages.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionPattern.res
- analysis/tests/src/expected/CompletionPattern.res.txt
Closes https://github.com/rescript-lang/rescript-vscode/issues/725
Adds very basic completion for `Exn.Error(error)` when switching on exceptions, plus links to the documentation on handling JS exceptions. This is a small thing but intended to increase discoverability of the `Exn.Error` API, which is hard to find otherwise unless reading the docs.
> basic completion for exn

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/ProcessCmt.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
Propagates deprecated status to completion for record fields and variant constructors.
> Propagate deprecated in more places

- analysis/src/DocumentSymbol.ml
Closes https://github.com/rescript-lang/rescript-vscode/issues/735
@cristianoc problem was that broken code like this:
```rescript
type observer = {next:}
```
...would produce a document symbol entry looking like this:
Notice `character: -1` in `end`.
Is the checking I'm doing unnecessarily much? I also found no good way to add tests for this since it's only happening in broken syntax.
> prevent broken locs from being added to document symbols

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
This prettifies how optional fields are printed in the completion detail.
Before:
```rescript
someOptionalField: option<int>
```
After:
```rescript
someOptionalField?: int
```
> prettify optional fields in completion detail

- CHANGELOG.md
- analysis/src/Commands.ml
- analysis/src/Completions.ml
- analysis/src/Hover.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Hover.res.txt
This leverages the new unsaved completion code to get hovers on some unsaved code.
I would eventually like this to also work on assigned identifiers, like (all unsaved):
```rescript
let fff = makeSomeRecord()
//   ^hov should show `someRecord`, but it doesn't because it doesn't handle the actual assigned identifier
let ccc = fff
//               ^hov here it works though
```
But this is a win nonetheless so adding support for something like that can be a separate thing.
> leverage new completion features to provide hover on (some) unsaved code

- analysis/src/CompletionBackEnd.ml
- analysis/src/Hover.ml
- analysis/src/SharedTypes.ml
Fixes https://github.com/rescript-lang/rescript-vscode/pull/749#discussion_r1133209576
> refactor and remove allFiles where not necessary to pass explicitly

- analysis/src/Packages.ml
- analysis/tests/src/expected/BrokenParserCases.res.txt
- analysis/tests/src/expected/CompletePrioritize1.res.txt
- analysis/tests/src/expected/CompletePrioritize2.res.txt
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- analysis/tests/src/expected/CompletionInferValues.res.txt
- analysis/tests/src/expected/CompletionJsx.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
- analysis/tests/src/expected/CompletionPattern.res.txt
- analysis/tests/src/expected/CompletionPipeChain.res.txt
- analysis/tests/src/expected/CompletionPipeSubmodules.res.txt
- analysis/tests/src/expected/CompletionTypeAnnotation.res.txt
- analysis/tests/src/expected/Cross.res.txt
- analysis/tests/src/expected/Debug.res.txt
- analysis/tests/src/expected/Destructuring.res.txt
- analysis/tests/src/expected/Div.res.txt
- analysis/tests/src/expected/ExhaustiveSwitch.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/Jsx2.res.txt
- analysis/tests/src/expected/Jsx2.resi.txt
- analysis/tests/src/expected/JsxV4.res.txt
- analysis/tests/src/expected/RecordCompletion.res.txt
- analysis/tests/src/expected/RecoveryOnProp.res.txt
- analysis/tests/src/expected/SignatureHelp.res.txt
See https://github.com/rescript-lang/rescript-compiler/pull/6091 where the jsx modules are moved inside Pervasives, to provide 2 different copies for curried and uncurried mode.
> Open Pervasives.JsxModules by default.

- analysis/src/SemanticTokens.ml
- analysis/tests/src/expected/Highlight.res.txt
- package.json
- server/src/server.ts
Neovim 0.9 add support for semantic tokens.
When opening a file and editing I get the following error: `E5248: Invalid character in group name`
I saw that the server registers tokens that are not in the specification: `support-type-primitive`, `jsx-tag` and `jsx-lowercase`.
This PR change name of tokens:
- `support-type-primitive` -> `type`
- `jsx-tag` -> `class` (`class` was used as module name, now it's `namespace`)
- `jsx-lowercase` -> `interface` (`div`, `h1`)
One question: Why emit a token for `jsx-tag`, the `<` and `>` in `<div>`? Couldn't this be done via regex?
Forum post: https://forum.rescript-lang.org/t/neovim-vim-rescript-lsp-semantic-tokens-issue-and-maintenance/4387
> Neovim client: fix semantic tokens

- CHANGELOG.md
- analysis/src/Xform.ml
- analysis/tests/not_compiled/DocTemplate.res
- analysis/tests/not_compiled/DocTemplate.resi
- analysis/tests/not_compiled/expected/DocTemplate.res.txt
- analysis/tests/not_compiled/expected/DocTemplate.resi.txt
- analysis/tests/src/expected/Xform.res.txt
- analysis/tests/test.sh
Add a code action to insert a docstring template. Only `.resi` files.
https://user-images.githubusercontent.com/16160544/234756643-03724a41-7009-47f2-8c29-000e5cc7def8.mp4
TODO:
> CodeAction: add docstring template

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/expected/CompletionExpressions.res.txt
This adds a `Some(fieldName)` case to completion when completing an option from a record field. 
Useful when you want to extract as variable whatever's in an option of a record field when pattern matching, and you typically end up calling that variable the same as the record field name anyway.
> Suggest field name in completion of options in record fields

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionExpressions.ml
- analysis/src/ProcessAttributes.ml
- analysis/src/ProcessCmt.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/src/Utils.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
We're able to generate function template/snippets for callbacks since a while back. But, given that the type information has no name for unlabelled arguments, we've been forced to call most variables in the generated template `v` (with a few notable exceptions that we've special cased). 
This PR improves how we infer template variable names by looking at the type path. For example, the type `Environment.t` would be called `environment` in templates, whereas `Environment.envConfig` would be called `envConfig`.
This can help the DX quite a lot, because we can capture _some_ of the variable name intent, at least for more complex types.
Before:
After:
I think this will be quite useful, but interested in hearing more thoughts.
> Improve generation of function template variable names

- analysis/src/Cmt.ml
- analysis/src/Packages.ml
- analysis/src/SharedTypes.ml
- analysis/tests/package-lock.json
- analysis/vendor/res_syntax/res_outcome_printer.ml
On hover,  uncurried type will now show without dot (in uncurried mode).
> Use uncurried mode setting for outcome printer

- CHANGELOG.md
- grammars/rescript.tmLanguage.json
implements https://github.com/rescript-lang/rescript-compiler/issues/6214
> Add syntax highlighting for raw JS code

- grammars/rescript.tmLanguage.json
- package.json
cf. https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages
> Enable basic JavaScript language features in FFI blocks

- CHANGELOG.md
- analysis/src/Commands.ml
Don't return a location with invalid range.
Close #779
> Fix invalid range

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionDecorators.ml
- analysis/tests/src/expected/Completion.res.txt
> Feat: add completion toplevel decorators

- CHANGELOG.md
- analysis/src/Cli.ml
- analysis/src/Codemod.ml
- analysis/src/Commands.ml
- analysis/tests/bsconfig.json
- analysis/tests/src/Codemod.res
- analysis/tests/src/expected/Codemod.res.txt
- server/src/codeActions.ts
This revamps the current "Insert missing cases" code action by leveraging actual AST transforms to produce the updated switch code instead of relying on unstable and ad hoc string parsing. This is now possible thanks to the compiler printing the cases in ReScript syntax rather than OCaml syntax.
Example:
> revamp insert missing cases code action

- CHANGELOG.md
- server/src/codeActions.ts
Allows for easily wrapping a pattern where an option is expected in `Some`. Useful as you change patterns from non-options to options, and need to update all parts of the pattern to be wrapped in `Some`.
Based on https://github.com/rescript-lang/rescript-vscode/pull/804 so that needs merging first.
> Code action: Wrap in Some

- CHANGELOG.md
- analysis/src/SignatureHelp.ml
- analysis/tests/src/SignatureHelpUncurried.res
- analysis/tests/src/expected/SignatureHelpUncurried.res.txt
This wasn't working in uncurried mode.
> Fix signature help in uncurried mode

- .github/workflows/ci.yml
This will make the `package` job crash less when simultaneous jobs run and they try to publish to the same version number.
> cancel running actions on new commits

- analysis/src/Cli.ml
- analysis/src/Codemod.ml
- analysis/src/Commands.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/Loc.ml
- analysis/src/TypeUtils.ml
- analysis/src/Xform.ml
- analysis/tests/src/ExhaustiveSwitch.res
- analysis/tests/src/expected/ExhaustiveSwitch.res.txt
- analysis/tests/src/expected/Xform.res.txt
- server/src/server.ts
This introduces a code action for inserting an exhaustive switch. Works for variants, polyvariants, options, and bools. It can be triggered in the following ways:
https://github.com/rescript-lang/rescript-vscode/assets/1457626/3f0a2ec7-3e1c-44fc-ae25-8a1912a59e0c
https://github.com/rescript-lang/rescript-vscode/assets/1457626/a9fcee90-5a5b-4bd7-b2fb-8e8b9315cfff
> Code actions for exhaustive switches

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionPattern.res
- analysis/tests/src/expected/CompletionPattern.res.txt
This makes the completion engine understand async/await.
> Make completion engine understand await

- CHANGELOG.md
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionPattern.res
- analysis/tests/src/expected/CompletionPattern.res.txt
This fixes a bug where for example completion from `result` wouldn't work, because the variant's type variables wasn't instantiated (and result is linked to `Belt.Result.t`, so I guess the type variables got lost in the linkage).
> Instantiate variant types as needed

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
Small quality of life improvement - when a function returns a promise, make the suggested function template async.
> Make function template async when fn returns a promise

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
Another quality-of-life thing. Previously, this: `someArray->Array.map(<com>` would ignore the pipe and complete as the first argument to `Array.map`, which would be the array itself, rendering a `[]` suggestion. With this change we instead get a function template suggested, like `v => {}`.
Next level on this would be to track the path/name of `Array.map` and change the suggested variable name in the function template to something nicer than the generic `v`, like `item`.
> Account for pipes in completion of single unlabelled argument

- CHANGELOG.md
- server/src/codeActions.ts
Was broken in v11 due to text it relied on having changed. Now works in both v10 and v11.
> Fix code action for inserting missing record fields for v11 of ReScript

- analysis/src/DocExtraction.ml
- analysis/tests/src/expected/DocExtraction2.res.txt
- analysis/tests/src/expected/DocExtraction2.resi.txt
- analysis/tests/src/expected/DocExtractionRes.res.txt
This is useful for generating submodule titles.
> [DocGen]: add module name field

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Hover.res.txt
Closes https://github.com/rescript-lang/rescript-vscode/issues/793
> resolve module aliases in hover

- analysis/src/DocExtraction.ml
- analysis/tests/src/expected/DocExtraction2.res.txt
- analysis/tests/src/expected/DocExtraction2.resi.txt
- analysis/tests/src/expected/DocExtractionRes.res.txt
Always emit the `items` key for modules. Top Level module emit `items`
> [DocGen]: Rename key `item` -> `items`

- analysis/src/DocExtraction.ml
- analysis/src/ProcessAttributes.ml
- analysis/src/ProcessCmt.ml
- analysis/tests/src/expected/DocExtraction2.res.txt
- analysis/tests/src/expected/DocExtraction2.resi.txt
- analysis/tests/src/expected/DocExtractionRes.res.txt
Emit all items from module alias.
```json
{
"id": "RescriptCore.Core__Console",
"kind": "moduleAlias",
"docstrings": [],
"signature": "module Console = Core__Console"
}, 
```
New Output:
```json
{
"id": "RescriptCore.Core__Console",
"name": "Console",
"kind": "moduleAlias",
"docstrings": [],
"items": [
{
"id": "RescriptCore.Core__Console.assert_",
"kind": "value",
"name": "assert_",
"signature": "let assert_: (bool, 'a) => unit",
"docstrings": ["`assert_(assertion, value)` print a message to console if `assertion` evaluates `false`. Does nothing if it's `true`.\n\nSee [`console.assert`](https://developer.mozilla.org/en-US/docs/Web/API/console/assert)\non MDN.\n\n## Examples\n\n```rescript\nConsole.assert_(false, \"Hello World!\")\nConsole.assert_(n == 42, \"The answer\")\n```"]
}, 
{ …
```
> [DocGen]: Polish

- analysis/src/FindFiles.ml
- analysis/src/Packages.ml
This accounts for the "public" setting in `bsconfig`. Seems like a fairly hidden property, but we should still support it imo given that trying to use something not listed in public (when public is set) is an error, even though items appear in autocomplete.
Example from the forum: https://forum.rescript-lang.org/t/how-to-only-expose-one-module-from-a-lib/4744/2
> Account for "public" setting in bsconfig

- analysis/src/DocExtraction.ml
- analysis/tests/src/expected/DocExtractionRes.res.txt
For some reason `formatCode` don`t print signature for some externals, see [Belt.Int](https://rescript-lang-fn6212fyj-rescript-association.vercel.app/docs/manual/next/api/belt/int#+)
`Shared.{type,decl}ToString` already does the formatting
Example:
```rescript
external \"-": (int, int) => int = "%subint"
``` 
Before:
```
{
"name": "Lib",
"docstrings": [],
"items": [
{
"id": "Lib.-",
"kind": "value",
"name": "-",
"signature": "let _: %rescript.typehole",
"docstrings": []
}]
}
``` 
After:
```
{
"name": "Lib",
"docstrings": [],
"items": [
{
"id": "Lib.-",
"kind": "value",
"name": "-",
"signature": "let -: (. int, int) => int",
"docstrings": []
}]
}
```
> Docgen(fix): Remove `formatCode` function

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Debug.res.txt
This fixes a very annoying issue where you wouldn't get autocomplete for "second order opens". I haven't added any tests because it'd be an incredibly noisy diff, but here's roughly what was wrong and what it caused:
1. Say you have an open in `bsc-flags`, like `-open RescriptCore`. Everything works as expected
2. The `RescriptCore` open exposes a bunch of modules like `Array`, `List`, `Result` etc. All of these are available in autocomplete. So far, so good.
3. Now, let's say you were to add an explicit open in a file for a module exposed via `-open RescriptCore`, like `open Array`.
4. The content of `Array` _won't_ be exposed to autocomplete in this case.
As can be seen by the minimal diff, this was a case of ordering. The list is reversed (correctly), but the order of `rawOpens` …
> Fix issue with ordering of module opened via -open

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
This handles filtering out namespaced modules when producing the relative completion path in pipe completion. 
Before (the issue is the namespace, that should be covered by `open Test` above):
After (namespace is now accounted for, which leads to `Test` disappearing correctly from the completion path):
> Account for namespace when filtering pipe completion items

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/src/Utils.ml
Fixes so that this hover of a namespaced module:
```rescript
module Test-RescriptBun: {
...
}
```
Instead becomes this:
```rescript
module Test: {
...
}
```
> Clean up hover of namespaced module

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/Utils.ml
We handled namespace file modules before, but other "exotic" file modules could still appear (example: `SomeTest.test.res`) which can't be used anyway. This filters anything with illegal characters in the name, for file modules specifically.
> Dont complete for illegal file module names

- server/config.md
> Docs: add server config

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/Utils.ml
This is a more robust implementation of https://github.com/rescript-lang/rescript-vscode/pull/843 that should cover all cases instead of just a few. Here, instead of checking for namespaces when filtering the completion items, we flatten any namespace items to their accessible paths before filtering. This allows the regular filter mechanism to just do its work like it's used to, and the filtering will work for namespaced items.
> More robust handling of namespaces in pipe completion

- analysis/src/Cli.ml
- analysis/src/Debug.ml
- client/src/commands.ts
- client/src/commands/code_analysis.ts
- client/src/commands/dump_debug.ts
- client/src/extension.ts
- client/src/utils.ts
- package.json
https://github.com/rescript-lang/rescript-vscode/assets/1457626/22de64c3-6531-4a55-8697-8b738d519f29
> Enhanced debug utils for extension dev

- CHANGELOG.md
- client/src/commands/create_interface.ts
> If interface exists, ask if it should be overwritten

- tools/CHANGELOG.md
- tools/package-lock.json
- tools/package.json
- tools/rescript.json
- tools/src/Tools_Docgen.res
- tools/src/Tools_Docgen.resi
- Fix tagged variant for `Module`
- Expose more functions
- Update to `rescript@11.0.0-rc.7`
Bump `@rescript/tools` to `0.2.0`
> Tools: fix tagged variant module and export more functions

- analysis/src/BuildSystem.ml
- analysis/src/Cfg.ml
- analysis/src/Cli.ml
- analysis/src/Packages.ml
- tools/CHANGELOG.md
- tools/src/Cli.res
This PR has one workaround to extract docs from the compiler repo and a fix
1. Introduce an env var `FROM_COMPILER` to analysis find the correct path to `cmt` files. In standalone packages, the `cmt` files are located in `lib/bs/`, but in the compiler repo they are in `lib/ocaml`
2. Add `stdio: "inherit"`. Node was truncating output when I run a separate process in `rescript-tools doc path/to/rescript-compiler/lib/ocaml/js.ml` https://github.com/nodejs/node/issues/2360
> Tools: enable doc extraction from compiler

- CHANGELOG.md
- server/src/cli.ts
- tools/CHANGELOG.md
- tools/src/Cli.res
```
➜ npm i -g @rescript/language-server
added 22 packages in 2s
2 packages are looking for funding
run `npm fund` for details
~ took 2s
➜ rescript-language-server -v
node:internal/fs/utils:350
throw err;
^
Error: ENOENT: no such file or directory, open './package.json'
at Object.openSync (node:fs:603:3)
at Object.readFileSync (node:fs:471:35)
at /home/pedro/.local/share/fnm/node-versions/v18.18.2/installation/lib/node_modules/@rescript/language-server/out/cli.js:28:49
at Object.<anonymous> (/home/pedro/.local/share/fnm/node-versions/v18.18.2/installation/lib/node_modules/@rescript/language-server/out/cli.js:38:3)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load …
```
> Fix Language Server and Tools `--version` command

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/Hover.ml
- analysis/src/Scope.ml
- analysis/src/SharedTypes.ml
- analysis/src/Xform.ml
- analysis/tests/src/CompletionInferValues.res
- analysis/tests/src/Reprod.res
- analysis/tests/src/expected/CompletionInferValues.res.txt
This fixes an infinite loop bug that was cause by not tracking the scope properly as we infer values from unsaved content. All inference worked on the same, final scope, which led to infinite loops when adding a new binding to scope with a name that was already in scope.
Now, each value in scope tracks its own scope properly, and this fixes the bug.
> Track scope properly when inferring values

- CHANGELOG.md
- server/src/cli.ts
- tools/CHANGELOG.md
- tools/src/Cli.res
> Fix Language Server and Tools --version command

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/src/Utils.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/ExhaustiveSwitch.res
- analysis/tests/src/Reprod.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/ExhaustiveSwitch.res.txt
(this is based off of https://github.com/rescript-lang/rescript-vscode/pull/869 for convenience, will rebase as soon as that is merged)
Fixes printing of polyvariants with exotic identifiers in completion etc.
Closes https://github.com/rescript-lang/rescript-vscode/issues/760
> Print exotic identifiers properly when completing polyvariants

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
Fixes so that you don't need to explicitly type a leading `#` to get completion when the underlying value is a polyvar.
> handle completion for polyvars without leading #

- analysis/src/CompletionFrontEnd.ml
- analysis/src/CompletionJsx.ml
- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/CompletionJsx.res.txt
Comment in the code says it all. Fixes an edge case where completing `<SomeComponent someProp=>` after `=` wouldn't work because the parser doesn't parse this the same as `<SomeComponent someProp= >` (which does work because we get an expr hole in `someProp=`).
> Heuristic for JSX completion happening at the very end of a component with children

- CHANGELOG.md
- analysis/src/Utils.ml
- analysis/tests/src/ExhaustiveSwitch.res
- analysis/tests/src/expected/ExhaustiveSwitch.res.txt
Hey,
Following up #870, we have now extended the functionality to also wrap polyvariant keywords with quotes.
> Extend quoting functionality to include polyvariant keywords

- analysis/src/DocExtraction.ml
- analysis/tests/src/expected/DocExtractionRes.res.txt
- tools/CHANGELOG.md
```bash
FROM_COMPILER=true ./analysis/rescript-editor-analysis.exe extractDocs ~/Desktop/projects/rescript-compiler/jscomp/others/belt.res | jq '{items}[] | map(select(.id == "Belt.Array")) | .[0] | .docstrings'
```
Before:
```
[
"[`Belt.Array`]()\n\n  **mutable array**: Utilities functions"
]
```
After:
```
[
"Utililites for `Array` functions.\n\n### Note about index syntax\n\nCode like `arr[0]` does *not* compile to JavaScript `arr[0]`. Reason transforms\nthe `[]` index synta
x into a function: `Array.get(arr, 0)`. By default, this\nuses the default standard library's `Array.get` function, which may raise an\nexception if the index isn't found. 
If you `open Belt`, it will use the\n`Belt.Array.get` function which returns options instead of raising exceptions. \n[See this for more …
```
> fix(tools): get docstrings from module file

- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/Packages.ml
- analysis/src/SharedTypes.ml
- analysis/src/Utils.ml
- analysis/tests/src/CompletionAttributes.res
- analysis/tests/src/expected/CompletionAttributes.res.txt
Adds basic completion for the string payload of the `@module()` attribute. A (pretty weird) example:
This is a basic version that will complete for:
- Package names in `dependencies` + `devDependencies` of `package.json`, if it can find it
- Local `.js` and `.mjs` files next to the source ReScript file
Ideas building on this:
- Resolve relative paths (completing `../` gives that folder contents, etc)
- Resolve `.d.ts` files relative to packages. Completing `next/` could give `next/link`, etc
One could maybe even go further and resolve `@scope` in combination with `@module`, and the external assignment, like:
```rescript
@module("next/link") external make: ... = "<com>"
```
And via that look up what exports there actually are in the `next/link` package. 
One can dream at least. This is a …
> Complete payload of @module attribute

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/tests/src/Hover.res
- analysis/tests/src/expected/Hover.res.txt
Closes https://github.com/rescript-lang/rescript-vscode/issues/790
> Expand type aliases when hovering

- CHANGELOG.md
- server/src/errorReporter.ts
- server/src/server.ts
- server/src/utils.ts
Instead report the error as a message, but only every 15 minutes.
We want people to report when things crash, but having the entire extension crash because of some potentially minor thing (code actions failing to resolve for example) is a bad experience. This makes sure that the extension does not crash when the analysis fails, but rather reports a message with the error (and not too often).
This is a good balance imo between getting people to report and preserving the UX of the extension.
> Do not crash entire extension when analysis fails

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
This is a QoL improvement intended to simplify the following scenario where you'd constructing a record without a type definition, but the expression is ambiguous and we don't know whether you're constructing a record yet or just typing some other expression:
```rescript
let someRecord = {
SomeModuleWithTheRecordDefinition.<com>
}
```
Previously you'd only get values from `SomeModuleWithTheRecordDefinition`, but with this change you'll also get any fields visible in that module.
> Include fields when completing for identifiers in a braced expr that is likely a module path

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionJsx.res.txt
- analysis/tests/src/expected/Div.res.txt
Change completion of DOM props of lowercase elements to try to look up `ReactDOM.domProps` first, before falling back to the current method of completing from a pre-defined list of DOM props (that was there because of JSXv3).
This is an adaption to JSXv4, and also a preparation for our upcoming generic JSX transform where we'll want to be able to swap out `domProps` to something custom for the generic transform.
> Complete lowercase JSX labels from the domProps type

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- analysis/tests/src/expected/CompletionTypeAnnotation.res.txt
A small touch up that makes sure we don't emit `_` unless we need to when completing in expressions. We emit `_` in patterns and that makes sense, but it doesn't make sense in expressions in all cases.
> Do not emit _ when completing expressions

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/CompletionSupport.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
Sometime we reach a `type t` from a module when completing expressions, and cannot go any further because `type t` might be abstract, or something we cannot complete. This is pretty common when using `type t` to hide implementation.
In those scenarios, it's a convention to provide `make` or other creator functions if the type can be constructed. This PR adds completions for all maker-style functions whenever constructing an expression where the expected type is `type t` and we can't go any further in the resolution.
This is going to make APIs where the type is abstract and hidden behind `type t` _a lot_ more discoverable.
Example from a classic situation where the value we're supposed to pass is an abstract `type t` that hides the implementation of `t` and has its own `make` function …
> Complete creator/maker functions for type t

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
- analysis/tests/src/expected/CompletionTypeAnnotation.res.txt
More cases of https://github.com/rescript-lang/rescript-vscode/pull/885
> More removal of _ in expr completion

- analysis/src/DocExtraction.ml
- analysis/tests/src/DocExtractionRes.res
- analysis/tests/src/expected/DocExtractionRes.res.txt
- tools/CHANGELOG.md
Closes #888
`Json.escape` was called twice:
- once explicitly
- twice in `Protocol.wrapInQuotes`
I also updated the test, to not contain e.g. `\\n`
Since this is my first PR in this repo, I hope this is fine?
> fix extracted docs of types include escaped linebreaks in signature

- analysis/src/CompletionBackEnd.ml
- analysis/src/DocExtraction.ml
- analysis/tests/src/DocExtractionRes.res
- analysis/tests/src/expected/DocExtraction2.res.txt
- analysis/tests/src/expected/DocExtraction2.resi.txt
- analysis/tests/src/expected/DocExtractionRes.res.txt
- tools/CHANGELOG.md
- tools/src/Tools_Docgen.res
- tools/src/Tools_Docgen.resi
Closes https://github.com/rescript-lang/rescript-vscode/issues/887
I've also removed all of the JSON decoding code, because with untagged variants we can just map to the result zero cost, which is a lot easier to maintain.
cc @aspeddro
> Support inline record fields in doc extraction

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionJsx.ml
- analysis/tests/src/CompletionJsxProps.res
- analysis/tests/src/expected/CompletionJsxProps.res.txt
Fix ambigious case where JSX brace wraps in JSX props are interpreted as a record body, but we dont know whether it actually is a record body or just wraps for the prop value itselfix ambigious case where JSX brace wraps in JSX props are interpreted as a record body, but we dont know whether it actually is a record body or just wraps for the prop value itself.
> Fix ambigious case with JSX brace wraps and record body

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionPipeChain.res
- analysis/tests/src/expected/CompletionPipeChain.res.txt
This fixes a fantastically annoying bug where pipe completion doesn't work inside of function calls, e.g: `Console.log(someArr->)`, completing on the empty pipe.
This covers at least the most common case, we'll see if there are more cases to handle too after this fix is shipped. I also feel like this is a bug that shouldn't even be possible if the completion engine does the right thing, so I'll add this to my (ever growing) "refactor completion engine" list.
But this fixes one of the annoying issues for now, so it's definitely worth shipping.
> Fix bug with pipe completion not working inside fn call

- tools/CHANGELOG.md
- tools/src/tools.ml
- tools/tests/src/ModC.res
- tools/tests/src/ModC.resi
- tools/tests/src/expected/ModC.res.json
- tools/tests/src/expected/ModC.resi.json
The output doesn't print docstrings for nested submodules in interface files.
Example: API Docs for [Core.Math.Constants](https://rescript-lang.org/docs/manual/latest/api/core/math/constants)
- [Core__Math.resi](https://github.com/rescript-association/rescript-core/blob/532af3a588a1144a5d867abc8e73a64e2d2b7c63/src/Core__Math.resi#L30-L33)
Now
```sh
dune exec -- rescript-tools doc ~/Desktop/projects/rescript-core/src/Core__Math.res | head
```
```
{
"name": "Core__Math",
"docstrings": ["Functions for interacting with JavaScript Math.\nSee: [`Math`](https://developer.mozil
la.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math)."],
"items": [
{
"id": "Core__Math.Constants",
"name": "Constants",
"kind": "module",
"docstrings": ["Mathematical Constants"],
```
- Print `deprecated` field …
> tools: docstring for nested submodules

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/Packages.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/CompletionPipeChain.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionPipeChain.res.txt
This enhances completion where the type is a regexp a bit, by:
- Preferring Core's `RegExp` module when Core is opened
- Adding a `%re("")` item automatically to the completion list in any place where a regexp value is expected
Small things, but should add some QoL.
> Enhance regexp completion

- analysis/src/Packages.ml
- analysis/tests/package-lock.json
- analysis/tests/package.json
- analysis/tests/src/Auto.res
- analysis/tests/src/Debug.res
- analysis/tests/src/Definition.res
- analysis/tests/src/ShadowedBelt.res
- analysis/tests/src/expected/Auto.res.txt
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- analysis/tests/src/expected/CompletionInferValues.res.txt
- analysis/tests/src/expected/CompletionJsx.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
- analysis/tests/src/expected/CompletionPipeChain.res.txt
- analysis/tests/src/expected/Debug.res.txt
- analysis/tests/src/expected/Definition.res.txt
- analysis/tests/src/expected/Destructuring.res.txt
- analysis/tests/src/expected/Div.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/RecordCompletion.res.txt
- analysis/tests/src/expected/SignatureHelp.res.txt
- analysis/tests/src/expected/Xform.res.txt
- tools/tests/src/expected/DocExtraction2.res.json
- tools/tests/src/expected/DocExtraction2.resi.json
- tools/tests/src/expected/DocExtractionRes.res.json
We now default to v11 in tests.
> up tests to ReScript v11

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionDecorators.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionAttributes.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionAttributes.res.txt
This experiments with improving completion for decorators by doing 2 things:
- Adding completion for the record you're supposed to pass into `@@jsxConfig`
- Adding better snippets for decorators that always needs a payload
> Enhance decorator completion

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionAttributes.res
- analysis/tests/src/expected/CompletionAttributes.res.txt
Adds completion for the new import attributes in `@module`.
> Completion for import attributes in @module

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionAttributes.res
- analysis/tests/src/expected/CompletionAttributes.res.txt
- Relax filter for what local files that come up in `from` and regular string completion in `@module`
- Make `from` completion trigger for expr hole so we get a nice experience when completing `{from: <com>}`.
> Enhance module attribute completion some more

- CHANGELOG.md
- analysis/tests/src/expected/CompletionJsx.res.txt
- analysis/vendor/res_syntax/jsx_ppx.ml
- analysis/vendor/res_syntax/jsx_v4.ml
- analysis/vendor/res_syntax/res_core.ml
- analysis/vendor/res_syntax/res_parsetree_viewer.ml
- analysis/vendor/res_syntax/res_parsetree_viewer.mli
- analysis/vendor/res_syntax/res_printer.ml
- analysis/vendor/res_syntax/res_scanner.ml
Closes https://github.com/rescript-lang/rescript-vscode/issues/915
> Latest version of parser

- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/CompletionJsx.res.txt
Just adding a simple test case so this is covered.
> Add test case for intrinsic elements

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
An example from our project. We have a `Money.zero` value and now it's also included in the autocomplete:
```
// Money.res
type t = string
let zero: t = "sdf"
let make = (): t => zero
let fromInt = (int): t => int->Js.Int.toString
```
```
// Money.resi
type t
let zero: t
let make: unit => t
let fromInt: int => t
```
> Add completion for type t values

- CHANGELOG.md
- grammars/rescript.tmLanguage.json
Solves: https://github.com/rescript-lang/rescript-vscode/issues/852
Solves: https://github.com/rescript-lang/rescript-vscode/pull/928
Inspired by: https://github.com/microsoft/TypeScript-TmLanguage/blob/a771bc4e79deeae81a01d988a273e300290d0072/TypeScript.YAML-tmLanguage#L2614-L2616
Before:
After:
> Improve syntax highligting for escaped characters

- grammars/rescript.tmLanguage.json
It shouldn't change anything (theoretically). It's a clean up pr to make `punctuation` grammar config more consistent to other fields.
> Grammar: Clean up punctuation config

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
Fixes an issue where completion inside of switch exprs wouldn't work because we iterate the cases instead when we shouldn't. 
Adds a bunch of debug logging as well.
> Fix issue where completion inside of switch expr would not work

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/CompletionJsx.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/CompletionJsx.res.txt
- analysis/tests/src/expected/Jsx2.res.txt
This fixes a bug that made empty prop expressions in JSX not complete if in the middle of a JSX element, because of the parser not being able to provide an expr hole for the empty prop expr (which in turn is because of valid reasons).
> Heuristic for JSX empty prop expr completion

- .github/workflows/ci.yml
- .vscode/launch.json
- .vscodeignore
- package-lock.json
- package.json
```
Archive:  rescript-vscode-8f6db88.vsix
Length      Date    Time    Name
---------  ---------- -----   ----
2736  2024-03-04 01:50   extension.vsixmanifest
583  2024-03-04 01:50   [Content_Types].xml
389  2024-03-04 01:50   extension/assets/switch-impl-intf-dark.svg
389  2024-03-04 01:50   extension/assets/switch-impl-intf-light.svg
29489  2024-03-04 01:50   extension/CHANGELOG.md
368876  2024-03-04 01:50   extension/client/out/extension.js
7318  2024-03-04 01:50   extension/client/package-lock.json
263  2024-03-04 01:50   extension/client/package.json
1111  2024-03-04 01:50   extension/grammars/rescript.markdown.json
13785  2024-03-04 01:50   extension/grammars/rescript.tmLanguage.json
1022  2024-03-04 01:50   extension/LICENSE.txt
8004  2024-03-04 01:50   extension/logo.png
437 …
```
> Bundle `client` and `server` with esbuild

- CHANGELOG.md
- server/src/config.ts
- server/src/incrementalCompilation.ts
- server/src/server.ts
Should fix https://github.com/rescript-lang/rescript-vscode/issues/943.
> Null checks for various extension config things

- CHANGELOG.md
- server/src/incrementalCompilation.ts
Just a few smaller stability fixes.
> Fixes for incremental compilation

- CHANGELOG.md
- analysis/bin/main.ml
- analysis/src/Commands.ml
- analysis/src/SignatureHelp.ml
- analysis/tests/src/SignatureHelp.res
- analysis/tests/src/expected/SignatureHelp.res.txt
- package.json
- server/src/config.ts
- server/src/server.ts
Made it possible to turn off if wanted. This can be quite useful - figure out what arguments a constructor takes (and where you're at with the arguments) via signature help. 
Examples:
> Extend signature help to also work on variant constructor payloads

- CHANGELOG.md
- server/src/codeActions.ts
- server/src/incrementalCompilation.ts
- server/src/server.ts
Code actions derived from error messages from incremental type checking weren't picked up before.
> Code actions from incremental checking

- analysis/bin/main.ml
- analysis/src/Cfg.ml
- analysis/src/CompletionBackEnd.ml
- analysis/src/SharedTypes.ml
- server/src/server.ts
A long overdue refactor. No need for 2 functions to exist. 
Also assumes all clients support snippets, which they do.
> Refactor: completion creation fns to just one

- CHANGELOG.md
- analysis/src/SignatureHelp.ml
- analysis/tests/src/SignatureHelp.res
- analysis/tests/src/expected/SignatureHelp.res.txt
Enables signature help for constructors in patterns.
> Signature help for constructors in patterns

- analysis/src/SignatureHelp.ml
- analysis/tests/src/SignatureHelp.res
- analysis/tests/src/expected/SignatureHelp.res.txt
> Enable signature help for option and result

- .github/workflows/ci.yml
`npm version preminor --preid next` increase minor version.
Example:
```diff
- "version": "1.22.0",
+ "version": "1.23.0-next.0"
```
install using `next` tag: `npm i -g @rescript/language-server@next`
> Add pre-release to `@rescript/language-server`

- CHANGELOG.md
- analysis/src/CompletionJsx.ml
- analysis/tests/src/CompletableComponent.res
- analysis/tests/src/CompletionJsxProps.res
- analysis/tests/src/expected/CompletionJsxProps.res.txt
This makes JSX completion work when make functions of type `React.component<props>`  are detected, like when using `React.lazy_`.
> Make JSX completion work for React.component

- grammars/rescript.tmLanguage.json
Fixes https://github.com/rescript-lang/rescript-vscode/issues/967
> Remove  not-existing #storage include in TextMate

- tools/CHANGELOG.md
- tools/bin/main.ml
- tools/src/tools.ml
Internal for now. Using it to experiment with the codegen approach I'm working on for ReScript.
> Add experimental command for extracting (string) contents from extension points

- .github/workflows/ci.yml
- analysis/vendor/res_syntax/jsx_v4.ml
Build with OCaml 5.1.1, like on the master branch of the rescript-compiler repo.
So that we can also use the same matching version of the docker container for the static Linux build which I'll add in a separate PR.
> Build with OCaml 5.1.1

- .github/workflows/ci.yml
- CHANGELOG.md
- analysis/bin/dune
- tools/bin/dune
* Build static binaries for Linux which fixes glibc compatibility issues. Uses same Docker container as in the rescript-compiler repo.
* Build Linux ARM binaries.
> Build static linux binaries, including arm64

- CHANGELOG.md
- analysis/bin/main.ml
- analysis/src/Cfg.ml
- analysis/src/Commands.ml
- analysis/src/Files.ml
This fixes the issue when you have an internal package in a monorepo and you click on a module from it in another package, you end up at `node_modules/@yourNamespace/yourPackageName`. Now it uses the real path and not the symlink anymore, so end up at the correct location.
> Use canonicalized URIs/paths for jump to definition

- CHANGELOG.md
- analysis/src/CompletionJsx.ml
- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/CompletionJsx.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/962
> Fix JSX prop autocomplete special case

- CHANGELOG.md
- analysis/src/CodeActions.ml
- analysis/src/Codemod.ml
- analysis/src/Commands.ml
- analysis/src/Protocol.ml
- analysis/src/Xform.ml
- analysis/tests/not_compiled/expected/DocTemplate.res.txt
- analysis/tests/not_compiled/expected/DocTemplate.resi.txt
- analysis/tests/src/Xform.res
- analysis/tests/src/expected/ExhaustiveSwitch.res.txt
- analysis/tests/src/expected/Xform.res.txt
Adds a code action to extract a module to a separate file.
1. Put your cursor on/inside of a defined module.
2. Choose "Extract module as file"
3. The locally defined module is now removed from the current file, and extracted into a separate "<moduleName>.res" next to the current file.
> Code action: Extract module to file

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/tests/src/CompletionTypeT.res
- analysis/tests/src/expected/CompletionTypeT.res.txt
Previously we would expand this into various maker-functions as well in patterns, which makes no sense.
> Do not expand type t in patterns

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/src/Xform.ml
- analysis/tests/src/Xform.res
- analysis/tests/src/expected/Xform.res.txt
Code action for expanding catch-all patterns. Useful when you want to go from a catch all to get exhaustive matching when you add new variant members, for example.
Works on:
- Variant
- Polyvariant
- Option of variant
- Option of polyvariant
Those are the ones I thought made sense to support without this snowballing in complexity.
> Code action: Expand catch all variant

- analysis/src/Xform.ml
- analysis/tests/src/Xform.res
- analysis/tests/src/expected/Xform.res.txt
Handle `Ppat_or` and guards in code action for expanding catch alls. Makes it a bit smarter.
> Extend code action that expands catch all

- CHANGELOG.md
- client/src/commands/code_analysis.ts
- client/src/extension.ts
- For the dead item itself
- Removing all dead items in the current file
Later on it'd be nice to have a command to run that can remove all of the dead code in a project. This might be better to do in `reanalyze` itself though? Or we can have an action in the editor that uses the editor to apply the edits. That would be easy to do as a first step. Although it'd only work in VSCode at first.
> Code actions for removing dead code

- analysis/src/Files.ml
This PR addresses a bug in the `canonicalizeUri` function that was causing issues with the `go to definition` feature in Neovim.
> preserve URI format in `canonicalizeUri`

- CHANGELOG.md
- analysis/bin/main.ml
- analysis/src/Cfg.ml
- analysis/src/Files.ml
With the fix from #990 tests run now fine without the workaround
> Remove workaround for canonicalize function in tests

- CHANGELOG.md
- analysis/src/CompletionExpressions.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
This fixes 2 cases that were broken when completing record fields in expressions:
- Starting to write out a new field name was mistakenly picked up as writing an ident for a field value, because of punning.
- The heuristic for whether you're intending to write a new record field picked up between fields (commas) but not at the start of the record body (`{`).
> Fix expr record field completion in existing records

- analysis/src/Xform.ml
- analysis/tests/not_compiled/expected/DocTemplate.res.txt
- analysis/tests/src/expected/Xform.res.txt
I don't believe this needs a changelog, we haven't released the original functionality yet.
> Clarify label for code action for extracting a local module

- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionPattern.res
- analysis/tests/src/expected/CompletionPattern.res.txt
Forgot to check for the cursor position when initiating pattern completion in a certain case.
> Fix issue where pattern completion would not be triggered

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionExpressions.res
- analysis/tests/src/expected/CompletionExpressions.res.txt
> Fix special case in switch expr completion

- analysis/src/ProcessCmt.ml
- analysis/src/SharedTypes.ml
- tools/npm/Tools_Docgen.res
- tools/npm/Tools_Docgen.resi
- tools/src/tools.ml
- tools/tests/src/DocExtractionRes.res
- tools/tests/src/expected/DocExtractionRes.res.json
Fixes https://github.com/rescript-lang/rescript-vscode/issues/902
@woeps please look through this and say what you think. A few things I can think of right away:
- We don't indicate when a module is implementing a module type. Not sure if this would be relevant for docgen.
- We can have id clashes now I guess, because I think a regular module and a module type with the same name can co-exist in the same module scope. So we need to account for that in the id generation.
> distinguish regular modules from module types

- tools/bin/dune
> rescript-tools: do not override flags for static linking

- tools/README.md
Reverts rescript-lang/rescript-vscode#1007 because it's obsolete due to #1013 .
releated to #1006
> Revert "add system requirements section for linux to tools readme"

- .github/workflows/ci.yml
This reduces macOS and Linux binary sizes significantly.
The total size of the VSIX drops from 19.3 MB to 14.5 MB.
> Strip binaries

- tools/CHANGELOG.md
- tools/src/tools.ml
- tools/tests/src/expected/DocExtractionRes.res.json
The example added in #925 don't print the module `M` structure
```rescript
module type Example = {
/***
this is an example module type 
*/
/**
main type of this module 
*/
type t
/**
function from t to t
*/
let f: t => t
}
module M: Example = {
/***
implementation of Example module type
*/
/**
main type 
*/
type t = int
/**
identity function
*/
let f = (x: int) => x
}
```
```
./node_modules/.bin/rescript-tools doc src/Demo.res
```
```json
{
"name": "Demo",
"docstrings": [],
"source": {
"filepath": "src/Demo.res",
"line": 1,
"col": 1
},
"items": [
{
"id": "Demo.Example",
"name": "Example",
"kind": "moduleType",
"docstrings": [],
"source": {
"filepath": "src/Demo.res",
"line": 1,
"col": 13
},
"items": [
{
"id": "Demo.Example.t",
"kind": "type",
"name": "t",
"signature": "type t", …
```
> Tools: Print module structure with signature to module path

- CHANGELOG.md
- server/src/incrementalCompilation.ts
- server/src/projectFiles.ts
- server/src/server.ts
- server/src/utils.ts
This reduces latency in the language server by caching a few project config related things, so that we most often don't need to do any potentially expensive lookups before we call the analysis, or invoke incremental typechecking.
Known issues with this approach: We need to recompute the ReScript version if it changes. I however don't believe we're watching anything already that can help us figure out when to recompute it. Will need to think a bit about how to do that. It's not a big problem though, because changing the ReScript version in a project does not happen often. And a restart of the language server (or closing all project files) will fix it.
> Reduce language server latency

- .github/workflows/bump-version.js
At least that is also how GitHub's own set output action does it, so it's worth a try.
https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L193
> Set GITHUB_OUTPUT instead of GITHUB_ENV in bump-version script

- .github/workflows/ci.yml
This reverts commit 873342bf5436d510ba60513abce5d1eefd5e8343.
Because it apparently broke PR builds without any error.
> Revert "CI: Reuse changelog entries for release notes"

- tools/bin/main.ml
- tools/npm/Tools_Docgen.res
- tools/npm/Tools_Docgen.resi
- tools/src/tools.ml
- tools/tests/src/expected/DocExtraction2.res.json
- tools/tests/src/expected/DocExtraction2.resi.json
- tools/tests/src/expected/DocExtractionRes.res.json
- tools/tests/src/expected/ModC.res.json
- tools/tests/src/expected/ModC.resi.json
Subset of https://github.com/rescript-lang/rescript-vscode/pull/1041
> Add additional signature information to doc json

- tools/CHANGELOG.md
- tools/npm/Tools_Docgen.res
- tools/npm/Tools_Docgen.resi
- tools/src/tools.ml
- tools/tests/src/expected/DocExtraction2.res.json
- tools/tests/src/expected/DocExtraction2.resi.json
- tools/tests/src/expected/DocExtractionRes.res.json
- tools/tests/src/expected/ModC.res.json
- tools/tests/src/expected/ModC.resi.json
After trying this in my own project, I noticed that the bindings were not 100% accurate.
> Correct ReScript bindings for signature details

- CHANGELOG.md
- package.json
- server/src/config.ts
- server/src/server.ts
- server/src/utils.ts
Enables incremental typechecking by default by changing the name of the prop (so old configs are invalidated) and setting a new default.
I'm sure there are more things we could do with incremental typechecking to make it a better experience, but at this point it's such a magnitudes better experience even with the small issues it might have. Enabling by default will make the experience better for everyone by default, and if issues surface we can fix them.
This also enables the `projectConfig` cache options, that dramatically reduce latency in certain scenarios.
> Enable incremental typechecking by default

- server/src/buildSchema.ts
- server/src/lookup.ts
Updates `ModuleFormat` to understand latest `rescript.json` `"module:" "esmodule"` config. This allows a user to use the `ReScript: Open the compiled JS file for this implementation file` option without it default looking for `/lib/js/src` instead of `/lib/es6/src`.
> Allow `esmodule` as a "module" option when compiling path

- analysis/tests/src/CompletionMultipleEditorCompleteFrom.res
- analysis/tests/src/CompletionPipeProperty.res
- analysis/tests/src/Rxjs.res
- analysis/tests/src/RxjsCompletion.res
- analysis/tests/src/expected/CompletionMultipleEditorCompleteFrom.res.txt
- analysis/tests/src/expected/CompletionPipeProperty.res.txt
- analysis/tests/src/expected/RxjsCompletion.res.txt
Hi @zth, I've added a few more test cases based on my last project I'm working on:
- `RxjsCompletion.res` it should complete from the parent module
- `CompletionPipeProperty.res` already works, could be interested to add for regression sake.
- `CompletionMultipleEditorCompleteFrom.res` didn't work a single attribute either. Seems interesting to have regression-wise.
> Additional completion tests

- CHANGELOG.md
- analysis/src/TypeUtils.ml
- analysis/tests/src/Firebase.res
- analysis/tests/src/expected/Firebase.res.txt
Port of https://github.com/rescript-lang/rescript/pull/7231
> Reuse original env when instantiating type

- .github/workflows/ci.yml
* No need for Docker anymore
* Get rid of BuildJet runner
> Build without docker, use GitHub Linux ARM runner

- CHANGELOG.md
- package.json
- server/config.md
- server/src/config.ts
- server/src/server.ts
- server/src/utils.ts
This removes the builtin formatter, since it has been doing more harm than good. 
One very concrete example is that code can be formatted differently if the ReScript compiler is installed vs not installed (different ReScript formatter version). But also things like https://github.com/rescript-lang/rescript-vscode/issues/1071.
Closes https://github.com/rescript-lang/rescript-vscode/issues/1071.
> Remove builtin formatter

- CHANGELOG.md
- server/src/server.ts
- server/src/utils.ts
I found out why the incremental build wasn't working yesterday.
Turns out I have a dot in my project folder name, this was mistaken for a file.
That file is not part of the project, thus the rescript version could not be found for the root.
> Use fs api to check if string is a directory.

- CHANGELOG.md
- server/src/incrementalCompilation.ts
If you compile a package inside a workspace, that package needs to be considered the root instead of the whole workspace when using rewatch.
> Fix local compilation when in a workspace

- CHANGELOG.md
- server/src/utils.ts
Fixes https://github.com/rescript-lang/rescript-vscode/issues/1079
I'm also in a little weird position where I use `nvm` on Mac, and somehow node is not always on my path anymore. This worked in the past, but is somehow broken for me, so I took a look in how I can get the LSP server working without depending on Node being present.
Turns out, the only thing I bump into is the initial rescript version call.
That will run `node_modules/.bin/rescript` which in the latest alpha has
```
#!/usr/bin/env node
...
```
For all the other stuff where we shell out to `bsc`, `rescript-editor-analysis`, we target the platform specific executable.
So, in this PR, I'm changing the version check to do the same. `bsc.exe -v` also produces the version we are after, prepended with `ReScript`.
> Use `bsc.exe` to figure out rescript version

- CHANGELOG.md
- grammars/rescript.tmLanguage.json
The grammar rule `RE_TO_DOWNTO_AS_LABELS` contains two patterns for ensuring that labelled arguments with names `to` and `downto` are highlighted as variables and not keywords.
The second pattern, `(to|downto)\s*(as)`, is supposed to match cases like `(~to as to2) => ...`, but was also matching e.g. `~toast`.
I've fixed this by changing `\s*` to `\s+`.
| Before | After |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/db853fc3-90a7-4ebe-a3ae-319522d6a960) | ![image](https://github.com/user-attachments/assets/18279901-adfa-4e84-899c-cf99de1ab0fe) |
> Require whitespace before `as` in `to`/`downto` labels

- CHANGELOG.md
- analysis/vendor/json/Json.ml
This is a backport of https://github.com/rescript-lang/rescript/pull/7435
More details about this fix can be found in that PR's description.
> Handle non-printable control characters when escaping JSON

- CHANGELOG.md
- server/src/incrementalCompilation.ts
The [`Not_included`](https://github.com/rescript-lang/rescript/blob/a87e656c6408f05f2686043cf7015c64b4a52a4e/compiler/ml/typemod.ml#L1817-L1818), [`With_mismatch`](https://github.com/rescript-lang/rescript/blob/a87e656c6408f05f2686043cf7015c64b4a52a4e/compiler/ml/typemod.ml#L1831-L1835) and [`With_makes_applicative_functor_ill_typed`](https://github.com/rescript-lang/rescript/blob/a87e656c6408f05f2686043cf7015c64b4a52a4e/compiler/ml/typemod.ml#L1836-L1840) errors from [`typemod.ml`](https://github.com/rescript-lang/rescript/blob/a87e656c6408f05f2686043cf7015c64b4a52a4e/compiler/ml/typemod.ml) use `Includemod.report_error` to report errors, which includes filepaths in its output.
Like in https://github.com/rescript-lang/rescript-vscode/pull/1086, by checking for the presence of these …
> Don't filter out module-related type errors

- CHANGELOG.md
- server/src/utils.ts
https://github.com/rescript-lang/rescript/pull/7395 split binaries into optional platform-specific dependencies (e.g. `@rescript/linux-x64`).
I've updated `utils.findPlatformPath` (used by `utils.findBscExeBinary` and `utils.findEditorAnalysisBinary`) to look for these platform-specific dependencies if `node_modules/rescript/{platform}` doesn't exist.
> Find per-platform binaries for v12.0.0-alpha.13+

- server/package.json
Presently, this package links to a 404 - Not Found error. This commit fixes the link.
> fix broken link on npmjs.org

- package-lock.json
- package.json
In https://github.com/rescript-lang/rescript-vscode/pull/1093 I added `semver` to `server/package.json` but in doing so accidentally removed it from the top-level `package.json`.
This broke the `package` job in the GitHub actions workflow: https://github.com/rescript-lang/rescript-vscode/actions/runs/15137696086/job/42554026987
> Restore semver package in top-level package.json to fix bump-version.js workflow

- server/src/server.ts
Fix for when the `lib/bs` folder is not in the root of a workspace.
> Add wildcards for watch registrations.

- CHANGELOG.md
- server/src/incrementalCompilation.ts
- server/src/utils.ts
See https://github.com/rescript-lang/rescript-vscode/issues/1091
Please take a look at this as well @mediremi
> Use platform specific rewatch binary

- CHANGELOG.md
- server/src/server.ts
Currently, opening a ReScript file in VS Code does not show existing compiler warnings and errors until a file change triggers `onWorkspaceDidChangeWatchedFiles`, which in turn calls `sendUpdatedDiagnostics`.
This fix calls `sendUpdatedDiagnostics` on file open, ensuring that users will see existing warnings & errors immediately.
> Show existing compiler warnings and errors on file open

- CHANGELOG.md
- analysis/src/SemanticTokens.ml
Backport of https://github.com/rescript-lang/rescript/pull/7750
> Trim trailing commas from semantic tokens output to ensure valid JSON

- CHANGELOG.md
- server/src/incrementalCompilation.ts
I believe this fixes https://github.com/rescript-lang/rescript-vscode/issues/1056 on Windows.
> Detect quoted path from ninja on Windows
