- CHANGELOG.md
- server/src/RescriptEditorSupport.ts
Fixes https://github.com/rescript-lang/rescript-vscode/issues/78
> Fix request failed when there's a white space in the project path.

- .github/workflows/ci.yml
- .gitignore
- analysis/.gitignore
- analysis/Makefile
- analysis/test.sh
- package-lock.json
- package.json
- server/analysis_binaries/README.md
- server/src/RescriptEditorSupport.ts
- server/src/server.ts
We did a subtree merge. Now it's time to adapt
> Truly integrate the recently merged rescript-editor-support

- CHANGELOG.md
- package-lock.json
- server/src/server.ts
See https://github.com/rescript-lang/rescript-vscode/issues/136
> Hook up command to go to references.

- CHANGELOG.md
- analysis/src/ProcessCmt.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Patterns.res
- analysis/tests/src/expected/Complete.res.txt
- analysis/tests/src/expected/Patterns.res.txt
https://github.com/rescript-lang/rescript-vscode/issues/165
> Fix issue jumping to variables defined in complex patterns.

- analysis/src/ProcessCmt.ml
- analysis/tests/src/Patterns.res
- analysis/tests/src/expected/Patterns.res.txt
And add a convoluted example of binding via variants.
> Complete complex patterns with variants and poly variants.

- server/src/server.ts
See issue #176.
Relevant diff for next time (cleanup, upgrade): #149
> Soft disable documentSymbol for now

- client/src/commands.ts
- client/src/extension.ts
- package.json
- server/src/constants.ts
- server/src/server.ts
- server/src/utils.ts
Similarly, other commands could be implemented (like convert .re to .res, or view ppxed source, etc.)
> Add command to create interface files

- CHANGELOG.md
- analysis/src/NewCompletions.ml
- analysis/src/PartialParser.ml
- analysis/src/References.ml
- analysis/tests/src/Div.res
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/Div.res.txt
- analysis/tests/src/expected/Jsx.res.txt
Show the type of, and jump to, `createDOMElementVariadic`.
Related: https://github.com/rescript-lang/rescript-vscode/issues/179
> Add support for lowercase jsx.

- .github/workflows/ci.yml
See https://github.com/marketplace/actions/set-up-ocaml
> ci: try latest supported ocaml action.

- server/src/server.ts
- server/src/utils.ts
> Fix formatting textedit range

- CHANGELOG.md
- analysis/.depend
- analysis/src/Hover.ml
- analysis/src/References.ml
- analysis/src/Utils.ml
- analysis/tests/src/Definition.res
- analysis/tests/src/expected/Definition.res.txt
See https://github.com/rescript-lang/rescript-vscode/issues/287
> Fix jump-to-definition for uncurried calls.

- CHANGELOG.md
- analysis/.depend
- analysis/src/Cmt.ml
- analysis/src/ProcessCmt.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Cross.res
- analysis/tests/src/DefinitionWithInterface.res
- analysis/tests/src/DefinitionWithInterface.resi
- analysis/tests/src/expected/Cross.res.txt
https://github.com/rescript-lang/rescript-vscode/issues/300
> Autocomplete pulls value from interfaces.

- CHANGELOG.md
- analysis/src/NewCompletions.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/Obj.res
- analysis/tests/src/expected/Completion.res.txt
Fixes https://github.com/rescript-lang/rescript-vscode/issues/321
> Support autocomplete of records for variables defined in other files.

- CHANGELOG.md
- analysis/src/Cli.ml
- analysis/src/Commands.ml
- analysis/src/DocumentSymbol.ml
- analysis/src/ProcessCmt.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/Completion.res
- analysis/tests/src/expected/Completion.res.txt
- server/src/server.ts
New implementation of documentSymbol for the outline using the parser.
This will avoid the problem of staleness, reason why it's been disabled so far.
> New implementation of outline.

- analysis/src/Completion.ml
The location of labelled arguments is stored as attributes in the AST.
This also fixes a crash when trying to extract the text of a label.
> Clean up extraction of labeled arguments.

- CHANGELOG.md
- client/src/extension.ts
- package.json
> feat: add restart language  server command

- analysis/tests/bsconfig.json
- client/src/commands/dead_code_analysis.ts
Use specifically `reanalyze@2.21.0` when starting dead code analysis.
This allows to configure the analysis via `bsconfig.json`.
> Analysis: use reanalyze 2.21.

- analysis/Makefile
- analysis/reanalyze/examples/deadcode/expected/deadcode.txt
- analysis/reanalyze/examples/deadcode/expected/exception.txt
- analysis/reanalyze/examples/deadcode/test.sh
- analysis/reanalyze/examples/termination/expected/termination.txt
- analysis/reanalyze/examples/termination/test.sh
- analysis/reanalyze/src/Reanalyze.ml
- analysis/reanalyze/src/dune
- analysis/src/Cli.ml
- analysis/src/dune
- client/src/commands/code_analysis.ts
e.g. `rescript-editor-analysis.exe reanalyze -dce`
> Use reanalyze embedded in the editor binary.

- analysis/src/CreateInterface.ml
- analysis/tests/src/CreateInterface.res
- analysis/tests/src/expected/CreateInterface.res.txt
Hello! I'm familiar with ReScript but it's my first try with OCaml. So if I did something wrong please feel free to correct me.
fix #425
> Fix interface generation if @inline is present

- analysis/reanalyze/src/EmitJson.ml
Fixes https://github.com/rescript-lang/rescript-vscode/issues/481
> Don't mix up printf and formatter.

- server/src/server.ts
Fixes https://github.com/rescript-lang/rescript-vscode/issues/496
> Fix issue in finding bsc binary.

- CHANGELOG.md
- README.md
- server/src/server.ts
- server/src/utils.ts
> Prevent dir from 'eating' the projectRootPath

- CHANGELOG.md
- analysis/src/Hint.ml
> Fix server crashers when open file is removed

- .github/workflows/ci.yml
Build command can be the same for all platforms.
> Simplify build command

- package.json
> Set display name and improve description for the VSCode package

- .github/workflows/ci.yml
> Use a static name for the latest-master artifact

- analysis/src/CompletionBackEnd.ml
- analysis/src/Packages.ml
- analysis/src/SharedTypes.ml
Naming changes, new modules etc, in the new stdlib. This adapts to that.
> adjust autocomplete to recent changes in stdlib

- CHANGELOG.md
- grammars/rescript.tmLanguage.json
Fixes https://github.com/rescript-lang/rescript-vscode/issues/671
> Highlight `catch`.

- analysis/src/Commands.ml
- analysis/src/CompletionBackEnd.ml
- analysis/src/Completions.ml
- analysis/src/Hover.ml
- analysis/src/SharedTypes.ml
- analysis/tests/src/CompletionPipeChain.res
- analysis/tests/src/expected/BrokenParserCases.res.txt
- analysis/tests/src/expected/CompletePrioritize1.res.txt
- analysis/tests/src/expected/CompletePrioritize2.res.txt
- analysis/tests/src/expected/Completion.res.txt
- analysis/tests/src/expected/CompletionExpressions.res.txt
- analysis/tests/src/expected/CompletionFunctionArguments.res.txt
- analysis/tests/src/expected/CompletionInferValues.res.txt
- analysis/tests/src/expected/CompletionJsx.res.txt
- analysis/tests/src/expected/CompletionJsxProps.res.txt
- analysis/tests/src/expected/CompletionPattern.res.txt
- analysis/tests/src/expected/CompletionPipeChain.res.txt
- analysis/tests/src/expected/CompletionPipeSubmodules.res.txt
- analysis/tests/src/expected/CompletionTypeAnnotation.res.txt
- analysis/tests/src/expected/Cross.res.txt
- analysis/tests/src/expected/Debug.res.txt
- analysis/tests/src/expected/Destructuring.res.txt
- analysis/tests/src/expected/ExhaustiveSwitch.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/Jsx2.res.txt
- analysis/tests/src/expected/Jsx2.resi.txt
- analysis/tests/src/expected/JsxV4.res.txt
- analysis/tests/src/expected/RecordCompletion.res.txt
- analysis/tests/src/expected/RecoveryOnProp.res.txt
- analysis/tests/src/expected/SignatureHelp.res.txt
start having a single entry point for completions
> Completion debug

- client/src/commands/code_analysis.ts
> Fix using wrong analysisProdPath on arm64

- CHANGELOG.md
- grammars/rescript.tmLanguage.json
> Grammar: Add pattern for single line ffi

- rescript.configuration.json
Auto close comments, type: 
```
/*
```
got:
```
/*| */
```
and press enter:
```
/*
|
*/
```
> Auto close and indent comments

- analysis/src/Utils.ml
Hello,
since #844 we don't have our modules listed in completion 
This PR fix that
> fix: add _ to charaters allowed in modules name

- analysis/tests/package-lock.json
- analysis/tests/package.json
- analysis/tests/src/expected/CompletionResolve.res.txt
> Update ReScript to v11.1

- CHANGELOG.md
- package.json
Fixes https://github.com/rescript-lang/rescript-vscode/issues/971
> Fix semanticTokenScopes override typescript files

- CHANGELOG.md
- analysis/src/Hover.ml
- analysis/tests/src/expected/Definition.res.txt
- analysis/tests/src/expected/DocComments.res.txt
- analysis/tests/src/expected/Hover.res.txt
- analysis/tests/src/expected/JsxV4.res.txt
> Hover: Print signature above docstrings

- CHANGELOG.md
- analysis/src/Cfg.ml
- analysis/src/Cmt.ml
- analysis/src/Commands.ml
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionDicts.res
- analysis/tests/src/expected/CompletionDicts.res.txt
- server/src/utils.ts
See comment in the code. A small adaption in incremental type checking mode that'll hopefully lead to more and more accurate completions.
> Use identifier loc in certain scenarios

- tools/README.md
put insights of #1006 into tools readme
@zth
> add system requirements section for linux to tools readme

- .github/workflows/ci.yml
> CI: Switch to action-gh-release and upgrade node

- CHANGELOG.md
- analysis/src/CompletionFrontEnd.ml
- analysis/tests/src/CompletionObjects.res
- analysis/tests/src/expected/CompletionObjects.res.txt
Fixes a bug where completions wouldn't show inside of obj bodies because they were never iterated.
> Iterate objects

- CHANGELOG.md
- analysis/src/CompletionBackEnd.ml
- analysis/src/CompletionFrontEnd.ml
- analysis/src/SharedTypes.ml
- analysis/src/TypeUtils.ml
- analysis/tests/src/CompletionJsx.res
- analysis/tests/src/expected/CompletionJsx.res.txt
Port of https://github.com/rescript-lang/rescript/pull/7292
> Add completion for React primitives

- server/src/incrementalCompilation.ts
Required for the changes from https://github.com/rescript-lang/rescript/pull/7551
> Update rewatch compiler-args for higher than alpha 14
